### ISSUE TITLE
TabMon installation issue- Postgres does not start 

### ISSUE THREAD

**Issue by anirudhpunuru** [tableau/TabMon#105]
Hey guys, Just started installing Tabmon, the installation went fine, but the services do not start. Here are the screenshots/log files. 

![image](https://cloud.githubusercontent.com/assets/14875335/21902648/b35afe9e-d8ca-11e6-9dae-463a2cd1cae9.png)

![image](https://cloud.githubusercontent.com/assets/14875335/21902667/c94e7cee-d8ca-11e6-89b1-8be052bbe1ed.png)

[TabMon.log.txt](https://github.com/tableau/TabMon/files/702530/TabMon.log.txt)

[TabMon.txt](https://github.com/tableau/TabMon/files/702532/TabMon.txt)

[DBCreation.txt](https://github.com/tableau/TabMon/files/702535/DBCreation.txt)

Any help is appreciated. 

Thanks :)

**Comment by jmangue** [comment]
Hi anirudhpunuru,

I took a look at your logs and it seems that TabMon is not able to authenticate with it's Postgres database.  It appears that during install, the Postgres database was not initialized correctly.  I can't tell from the logs as to why that may have happened, and can only speculate that it may have been permissions related.

Your best bet for getting into a good running state would be to:

1. Uninstall TabMon and remove the TabMon-Postgres service using the "Uninstalling TabMon & Postgres" instructions at the end of the user guide
2.  Reinstall TabMon but **deselect** "Install Postgres for me".  
3.  Follow the "Manually Installing & Configuring Postgres" section in the user guide to set up the database.

Let me know how it goes!

**Comment by anirudhpunuru** [comment]
Thanks for the reply. I installed postgres manually. Here is the attached log, I see that tabmon has started fine, but postgres hasn't started. When I see the log, it looks to be writing/creating records. But, when I open the sample workbook, it is blank- all the sheets(I do see records in the tabmon datasource- 500 of them. 

[TabMon (2).txt](https://github.com/tableau/TabMon/files/711422/TabMon.2.txt)

![image](https://cloud.githubusercontent.com/assets/14875335/22025859/115c72f4-dc9d-11e6-9dc5-4b3d5b61b519.png)

![image](https://cloud.githubusercontent.com/assets/14875335/22025881/1f45e260-dc9d-11e6-8f13-af2acc1ff1f1.png)

**Comment by jmangue** [comment]
Hi anirudhpunuru,

Did you remove the existing TabMon-Postgres service first as I mentioned in step #1?

I ask because if you removed the existing one and then installed Postgres manually, that service should no longer exist; the manually installed db will have a different name, usually starting with "postgresql".

**Comment by anirudhpunuru** [comment]
Yes, I did remove the exisiting postgres. I do see another service called postgres- which is working fine. Wonder why this is shown. Also, I did manage to get to see the sample workbooks with the tabmon data.

**Comment by jmangue** [comment]
Closing this out due to inactivity.

Anirudhpunuru, please reopen if you still need help with this issue.
