### ISSUE TITLE
CPU usage 

### ISSUE THREAD

**Issue by suniltikar** [tableau/TabMon#106]
Hello,

We just recently configureed TabMon . We were looking at TabMon.twb file and dashboards and found there is no CPU usage information ,there is % processing time but our need is to show what the % CPU utilization (something like below example) 
![1-24-2017 2-45-55 pm](https://cloud.githubusercontent.com/assets/20704119/22264317/78ceb138-e245-11e6-8b29-8b893003974d.jpg)

Is there any way we can get that information ..like wise if I have a cluster of 5 machine ,1 primary and 4 workers . Each machine having 16 croes . Can we get the information % utilization of Cores(CPU) on each worker on a given time frame .

Regards ,
Sunil

**Comment by danjrahm** [comment]
Hello Sunil, 

We should natively pull the CPU utilization. Can you send me the tabmon logs? The can be found here:
<TabMon Install Root>\TabMon\Logs\TabMon.txt

These will tell me whether there is an issue pulling that counter.

Thanks,
Dan

**Comment by danjrahm** [comment]
Hey Sunil,

I'm just checking in to see if you still require assistance. Please let me know.

Thanks,
Dan

**Comment by jmangue** [comment]
Closing this issue as stale due to age.  Sunil, please reopen if you need help.
