### ISSUE TITLE
Require TabMon Workbook 10.0v

### ISSUE THREAD

**Issue by kmohiddin** [tableau/TabMon#107]
Hello,

This is regarding case # 02693058. 

We have captured Performance metrics in a CSV format for Tableau server. We are facing issues while trying to open the result CSV file in TabMon workbook.

As discussed in our previous call, one among the solutions is to check the version of TabMon workbook. Version needs to be same for Tableau desktop and TabMon. The version of TabMon that we are using here is 9.3 and We have Tableau desktop 10 installed . Below is the version line mentioned in the screenshot for your reference. 

We have downloaded the latest version of TabMon from the  link provided (https://github.com/tableau/TabMon/blob/master/TabMon/Resources/Sample%20Workbooks/9.3%20-%2010.0/TabMon.twb) but we could not find 10.0 version in Git hub. Kindly provide us the link/url for 10.0v file.

**Comment by danjrahm** [comment]
Hello,

The 10.0 workbook is included in the TabMon install. To find it please replace the root place holder and go to the directory below.
<TabMon Install Root>\TabMon\Resources\Sample Workbooks\9.3 - 10.0

This directory will contain the 9.3-10.0 workbook.

**Comment by kmohiddin** [comment]
The workbook in \TabMon\Resources\Sample Workbooks\9.3 - 10.0 is of version 9.3. We could not find version 10. Kindly help us on this

**Comment by Naiana-Tableau** [comment]
The workbook in "\TabMon\Resources\Sample Workbooks\9.3 - 10.0" is for version 9.3 to version 10 
If you have the workbook from this location, you have the correct one for version 10

**Comment by danjrahm** [comment]
Hey kmohiddin,

Naiana-Tableau is correct. The workbook in that directory spans both versions of Tableau. If there are any further issues let me know. 

Until then, I am closing this out.
