### ISSUE TITLE
Tabmon SSL Issue

### ISSUE THREAD

**Issue by MallikaKM** [tableau/TabMon#108]
![tabmon error](https://cloud.githubusercontent.com/assets/23288450/23360717/fc440710-fd12-11e6-8491-20b56d35a8b7.JPG)
Hi,

Im facing the issue with connecting to Tabmon Postgresql from Tableau Desktop. I'm getting the attached Error, please help to setup the Postgresql to which supports to Tabmon.

Thank you

**Comment by rahulmotwani** [comment]
@MallikaKM, thanks for the feedback. SSL is not supported right now and is a feature request we are tracking - see [https://github.com/tableau/TabMon/issues/94](url)
