### ISSUE TITLE
Feature Request: Sample timestamps should be in UTC instead of local time

### ISSUE THREAD

**Issue by LelandWeathers** [tableau/TabMon#109]
Please log TabMon datetime stamps in UTC time instead of localtime (pollTimestamp = DateTime.UtcNow()) or at least store in the db with offset. 

Time Zone offsets in TabMon.twb would then only change the display time and not need to convert times in between TabMon db and the Tableau PostgreSQL repository alleviating issues with daylight savings time changes, etc.

This change would support easier downstream uses of the data (aggregation for longer-term capacity management planning etc...)

**Comment by jmangue** [comment]
Hi Leland,

Thanks -- this is a great request, and should be pretty easy to implement (especially since you already pointed out the solution in both the code and the workbook).  Marking this as a future enhancement, hopefully for the next version.

**Comment by danjrahm** [comment]
This issue has been released by v1.2. Closing now.
