### ISSUE TITLE
How to regenerate TabMonConfigReader.cs after changing the xsd

### ISSUE THREAD

**Issue by tfoldi** [tableau/TabMon#11]
Hello,

I am extending TabMon with a few configuration item using Visual Studio 14 Community edition. After changing the xsd file I do not see any option to regenerate the `TabMonConfigSection.cs` file. Also, the build does not re-generate it.

What should I do? Could you complete the developer docs including the required tools and processes for the config file schema changes?

Many thanks

**Comment by jmangue** [comment]
Hi tfoldi, good callout on this.  In response I just pushed up feature branch "CustomConfigSection" which contains the TabMonConfigSection.cs and TabMonConfig.xsd schema generation project, as well as some light documentation on how to regenerate them.

We aren't actually using the XSD to generate the CS file; rather, we generate both using a CSD file that the "Configuration Section Designer" extension for Visual Studio gives you a visual editor for.  Let me know if you have any question how to use this.

On a side note, I think it's awesome that you're extending TabMon!  If you develop a feature of value to the core project, feel free to push it back once complete.

**Comment by tfoldi** [comment]
Thank you. 

Am I seeing correctly that this extension does not support Visual Studio 14.0 Community Edition? What is the VS env what you're using?

**Comment by jmangue** [comment]
Hi tfoldi,

I am using VS 2013 Premium.  That's a bummer about the CSD extension not working in the newest version.  It looks like a lot of people are complaining about that on the "Discussions" board of the Codeplex site, and some have suggested workarounds which might work.

**Comment by tfoldi** [comment]
I will check those workarounds, thank you.
