### ISSUE TITLE
PGAdmin3 - I can't create a New Login Role

### ISSUE THREAD

**Issue by BPinuela** [tableau/TabMon#110]
As soon as we saw the capabilities of this tools, we were/are very interested in using it. Congratulations for it!

We have tried to install TabMon following the installation guide, but we have already installed PostgreSQL. We are running Tableau Server 9.3

We are already using readonly user to connect to the workgroup database. But we try to create the tabmon user following Appendix A point 3. The point is that we connect to the database with the readonly user but with this user when we right click on "login roles" to create a new one we do not have this option available. We have seen that a user named tblwgadmin could have that privilege but when trying to create the password as we did with readonly user,  it fails. So, we are stopped here.
In addition to that when we use the PostgreSQL database workgroup we are using the port 8060. I saw in your installation guide your using 5432. ¿?
Another question we are concerned is:  could this installation affect somehow to our published tableau datasources? (This is a production environmen running right now)

Many thanks for you help

**Comment by jmangue** [comment]
Hi BPienuela

Do not use Tableau Server's Postgres database for TabMon -- especially in a production environment.  TabMon requires a separate PostgreSQL instance to minimize both chance of data corruption and performance impact on your Tableau Server instance.  In general, we recommend you never make any manual modifications to your Tableau Server PostgreSQL instance unless advised to do so by Tableau Technical Support.

Fortunately the TabMon installation guide has instructions on how to set up a separate PostgreSQL instance.  😄 

Let us know if you have any issues setting up the standalone TabMon PostgreSQL instance.  Closing this issue out for now.
