### ISSUE TITLE
Tab config changes

### ISSUE THREAD

**Issue by Tabuser** [tableau/TabMon#113]
Hi,

I have new nodes to my existing cluster and I need to add them to the tabmon config file which I am fine doing. My question is, do I need to stop the tabmon services to do the changes and restart again? or modifying the config and saving back in the config directory is good enough?

Thank you!
Tabuser

**Comment by rahulmotwani** [comment]
Yes, you will need to stop/restart the service again for the config changes to be picked up successfully. Let us know if you run into issues doing this.
