### ISSUE TITLE
Check TabMon Status

### ISSUE THREAD

**Issue by MallikaKM** [tableau/TabMon#114]
Please let me know, how to check the status of TabMon, is up and running.

Note: CMD command / Scripts is available to check other thasn go to service and check manually

**Comment by jmangue** [comment]
Hi MallikaKM,

You can check the status of TabMon using the following CMD command:

>sc query TabMon

You can also use this remotely if TabMon is on another computer on your network, e.g.:

>sc query \\\mytabmonserver.lan TabMon

These commands will work with any Windows service 😃 

Closing this out, please reopen it if you need additional help with this issue!

-Justin

**Comment by MallikaKM** [comment]
Thank you Justin.

I tried pg_ctl command with path for Start & stop the Postgres. No luck.

Could you please share the command for "Starting & Stop the Tabmon Postgres db"

**Comment by MallikaKM** [comment]
Hello Dan,

Thank you for the reply.

I'm  getting a below error wen i use this command

[SC] open command failed 1060
The specified service does not exist as an installed service

We have installed Tabmon in D:\Tabmon & Postgres in C:\Program
files\pistgreSQL. Is this make any difference?

Regards,
Mallika

**Comment by danjrahm** [comment]
That would mean that the service postgres is installed under is not named TabMon-Postgres.

In order to find that you'll need to look in the services list for the computer.

**Comment by MallikaKM** [comment]
Yes, got it. I run the command with SC start service name. Got an error# 5.
Same cmd run with administrative tool, this cmd working fine.

Thank you so much for your help.

Regards,
Mallika

On Apr 2, 2017 11:30 PM, "Daniel Rahm" <notifications@github.com> wrote:

That would mean that the service postgres is installed under is not named
TabMon-Postgres.

In order to find that you'll need to look in the services list for the
computer.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tableau/TabMon/issues/114#issuecomment-291002996>, or mute
the thread
