### ISSUE TITLE
embed latest view in mail

### ISSUE THREAD

**Issue by rishabh1991** [tableau/TabMon#118]
Hi Team,

Currently I am using batch file and html code to embed view in mail from tableau server. But somehow the updated image is not getting embedded in mail.
How to achieve the latest image in the mail.

Thanks 
Rishabh

**Comment by jmangue** [comment]
Hi Rishabh,

This is really a Tableau Server question, not than a TabMon question.  I recommend you contact Tableau Technical Support or ask for assistance on the Tableau Server community forums.

Thanks!
