### ISSUE TITLE
Sample Workbook 9.3 - 10 is blank

### ISSUE THREAD

**Issue by cj1989** [tableau/TabMon#119]
Hi, 

I have recently installed TabMon on the same server hosting my Tableau Server.  I found the installation smooth, and your User Manual helpful.  Howerver, when I open the Sample Workbook TabMon.twb ALL dashbords appear blank.

I noticed someone else had a similar issue (in the Closed Issues section), but changing the Time Zone Offset and filters at the top only partially allows views to show up.  To make the front dashboard show up like in the second image below I have to do a lot of manual tinkering with 'Use as Filter' function and I'm not sure if its working as intended.  And I assume I'll have to do it for all the other dashboards included.

The Tableau Desktop version I am using is 64 bit 10.0.  Is anyone else experiencing similar issues?
Blank:
![image](https://cloud.githubusercontent.com/assets/28972539/26480709/21db88ee-421f-11e7-8d02-3aa3dae0d689.png)

Removing Alot of Filtering Manually:
![image](https://cloud.githubusercontent.com/assets/28972539/26480839/169dc554-4220-11e7-879d-536cdeec7a70.png)

**Comment by danjrahm** [comment]
Hello,

I can take a quick look at the workbook to validate the data is you're willing to attach it to this issue. To attach it, first take an extract of the countersamples data source. Next, create a packaged workbook and attach it to this issue.

If this isn't an option let me know. We'll figure out another way to validate the data.

Thanks,
Dan

**Comment by rahulmotwani** [comment]
Closed due to inactivity. Please reopen if you still need help.
