### ISSUE TITLE
Unable to enable remote access to Postgres datbase

### ISSUE THREAD

**Issue by discontentpanda** [tableau/TabMon#123]
Hi,
I've installed tabmon on a seperate EC2 box.  It's working fine to access views from localhost.  However, I cannot get remote access to work.  I've added our ipv4 line to the config file.  I've tried do a broad address like 10.0.0.0/8 and even computer specific IP addresses to no avail.  Our previous Tabmon box worked fine with the 10.0.0.0/8 and I copied the settings over with no luck. Not sure if you can help since it's a postgres issue.  Am I missing another remote setting besides the one in the pg_hba.conf file?   This is a new EC2 instance that I've already enable remote desktop access to as well.

Thanks for listening, been trying to fix it for 6 plus hours.

**Comment by jmangue** [comment]
Hi @discontentpanda,

I don't have firsthand experience on running TabMon on EC2.  I'm assuming that the problem you're describing is the inability to connect to Postgres remotely.

A couple things to try:
- Check postgresql.config and set [listen_addresses](https://www.postgresql.org/docs/9.5/static/runtime-config-connection.html) to '*'
- Make sure your firewall settings enable traffic to port 5432

Beyond that, I'm a bit stumped... you could try seeing what other people have done online, such as [this StackOverflow article](https://stackoverflow.com/questions/14545298/connect-to-remote-postgresql-server-on-amazon-ec2).

Good luck!

**Comment by slewt** [comment]
If you haven't already looked, should double check security groups at both the ec2 instance and the vpc. If those aren't blocking traffic then may then need to check any it is in and also any elastic IPs assigned correctly.

**Comment by slewt** [comment]
bad english there. if security groups are good then should check elastic IPs are correct and present.

**Comment by jmangue** [comment]
Thanks for helping out, @slewt.

**Comment by discontentpanda** [comment]
Turns out it was my own user error.  I was using note pad to save the config file but didn't save it as a .conf file. It was turning it to a .txt file instead. Problem solved. Thanks all.

**Comment by jmangue** [comment]
Glad you got it working @discontentpanda :smiley: It happens to the best of us!  Closing this out.
