### ISSUE TITLE
Issue Regarding Tableau Desktop over Citrix 

### ISSUE THREAD

**Issue by rishabh1991** [tableau/TabMon#124]
Hi Team,

I have installed tableau desktop in citrix environment. I are getting error while activating product key:
![issue](https://user-images.githubusercontent.com/17762245/27335134-25603bb2-55e9-11e7-99e8-372987b86110.PNG)

Please let me know what needs to be done?

Thanks 
Rishabh

**Comment by rahulmotwani** [comment]
Hi @rishabh1991,

Sorry to hear you are experiencing issues with activation with Tableau Desktop. Unfortunately, this is not the correct forum for this question - this is only related to questions around TabMon. Check the Tableau Communities site to post and check on existing issues - https://community.tableau.com/welcome. 

In particular, check out this thread which might address your issues: https://community.tableau.com/message/194762#194762
