### ISSUE TITLE
Bug: Tableau Instrumentation JMX counters returning null values in newer versions of Server

### ISSUE THREAD

**Issue by jmangue** [tableau/TabMon#126]
The MBean paths for "Tableau Instrumentation" JMX counters recently changed in 10.1 or 10.2 to include a root "methods" path segment.  This results in sampling of these counters failing.  We will need to release a new version of the bundled Counters.config to include support for the new path names.

A workaround in the meantime is to take the default Counters.config file and prepend `type=methods,` to all of the TableauInstrumentation node path attributes.

For example, `path="00=worker,01=refreshExtracts,name=execute"` should be updated to `path="type=methods,00=worker,01=refreshExtracts,name=execute"`

**Comment by danjrahm** [comment]
This issue has been released by v1.2. Closing now.
