### ISSUE TITLE
 relation "public.countersamples" does not exist

### ISSUE THREAD

**Issue by AsifNihaz** [tableau/TabMon#127]
Hello Team,

   I'm getting relation "public.countersamples" does not exist when i tried to open the workbook after installation.

Tried below things to resolve below the error but no luck.

1) Uninstalled as per guidelines give in the user guide and Reinstalled the Tabmon.
2) installed postgres in different drive

Thanks,
Asif.

**Comment by jmangue** [comment]
Hi Asif,

I took a look at your logs.  It looks like initially you had TabMon configured to collect counters from localhost/CSDCBI, and it was successfully collecting data, but then a configuration change was made to point TabMon at "intranetbi" instead.

Judging by the logs, the simple machine name "intranetbi" is not resolving, so no data is being collected and thus no data is being written to the database.  You could try setting the Host name in TabMon.config to point to the output of the `hostname` command on the target machine, and then restart the service to fix this.  Let me know how it goes!

**Comment by danjrahm** [comment]
Closing this out due to lack of activity.
