### ISSUE TITLE
Feature Request: Option to automatically purge data older than a certain threshold

### ISSUE THREAD

**Issue by jmangue** [tableau/TabMon#13]
Add the ability to have the application automatically delete old data based on timestamp, controllable via config options

**Comment by danjrahm** [comment]
This is in pull #81. Currently testing once test is complete/successful this will be closed.

**Comment by danjrahm** [comment]
All testing is successful. Will close on our final merge.

**Comment by danjrahm** [comment]
Purge data feature is complete and merged. Closing this now.
