### ISSUE TITLE
TabMon and JMX Port Access Issue

### ISSUE THREAD

**Issue by jody-bossle** [tableau/TabMon#145]
Installing and configuring TabMon 1.2 in an environment with two (2) distributed 3-node clusters (one 3-node cluster for DEV and one for PRD).  Each cluster has a Primary (Gateway, Search & Browse), Worker 1 (all services, active repository), and Worker 2(all services, passive repository).  DEV is currently running Tableau Server 10.3.3 and PRD is 10.3.2; PRD will be upgraded shortly.

JMX has been enabled on all cluster servers and confirmed in the tabsvc.yml file

TabMon is running on a separate server, not part of either cluster, is configured to collect both PerfMon and JMX metrics.

TabMon is running under a domain service account and that service account has been added to the local Administrators, Performance Log Users and Performance Monitor Users groups on all servers.  

Performance Logs & Alerts and Remote Registry services are running on all cluster servers

TabMon starts as expected and is collecting PerfMon metrics on all 6 cluster servers.  TabMon ONLY collects JMX metrics on PRD Worker 2.  

A review of the TabMon log file reports "Encountered closed JMX port (xxxx), stopping scan." on all JMX ports for 5 of the cluster servers when TabMon starts up; PRD Worker 2 is the only server where the JMX ports are opened.

A comparison of NETSTAT -AN output run on all 6 cluster servers shows:
1) There are no JMX ports listening on the DEV and PRD Primary (Gateway, Search & Browse); understood and expected.
2) JMX ports are active and listening on all Worker servers

Configuration has been checked and re-checked.  TabMon has been uninstalled and reinstalled, this issue is repeatable.

Any ideas would be appreciated.

**Comment by jmangue** [comment]
Hi @jody-bossle ,

Interesting.. does your netstat output show that the JMX ports being listened to on the other workers are the same ports as what is currently working on PRD Worker 2?  TabMon is scanning starting from the base ports as specified in the Counters.config file, so verifying that those ports are active and listening on the other workers would be something to check.

Are there any other differences you can think of between PRD Worker 2 and the other workers, such as a firewall configuration?

**Comment by jody-bossle** [comment]
Justin,

Thanks for the reply.

Firewall has been ruled out; OS firewalls are disabled across our domain
via enforced group policy.

I double-checked the JMX ports on the Tableau site (8300 - 8359, 8550,
9095, 9400 - 9499, and 10000 - 10299).  I then extracted the ports
"listening" on each of our two DEV and two PRD worker servers using "*netstat
-an -p tcp | find "LISTENING" > netstat_wrkr-xxx_listening.txt*".  Finally,
I compared the list of JMX ports to the NETSTAT outputs and found ALL four
4 worker servers are listening on the following ports: 8550, 9400, 9401,
9402, 9403, 10000, 10001, 10002, 10003; there are no outliers/extra JMX
ports listening on any of the 4 servers.  With that said, I feel there are
ports missing; note: I consider myself to be an advanced Windows server
administrator, but not an expert and networking would be my Achilles heel.
I am following up with our network and advanced server teams for guidance
but any additional insights would be helpful.

Thanks,

Jody

-----------------------------------------------------------------------------------------------------------------------------

**Comment by jmangue** [comment]
Hi Jody,

It sounds like you are on top of things.  I don't have any additional insights beyond what we've talked about, but I can recommend a troubleshooting technique to you... you could try manually connecting to the JMX ports directly using the JConsole utility.  Unfortunately this is not super well document but there is some guidance on how to do this up in [Russell Christopher's blog ](http://tableaulove.com/tabmon-is-a-detective-for-tableau-server/).  

Ideally, you could try testing connecting to the JMX ports on one of the workers from the machine that TabMon installed on.  This should give you a hint as to whether the problem lies with TabMon or not.

**Comment by danjrahm** [comment]
Due to inactivity, I am going to close this.

**Comment by jody-bossle** [comment]
Dan,

Can you please re-open?  I am still having issues, but was out of the
office for surgery and I'm just getting back.  Plan to look at this next
week after I did out.

Regards

Jody

-----------------------------------------------------------------------------------------------------------------------------

**Comment by danjrahm** [comment]
Can do. I am reopening now.

**Comment by jody-bossle** [comment]
Dan,

So, as a Tableau server admin I consider myself a novice; as an overall
server administrator, I'm seasoned but not an expert.  It appears TabMon is
up and running and I can see the *CPU*, *Memory*, *Network* and *Disk* data
for my 3 DEV servers (1 gateway and 2 workers) and 3 PRD servers (1 gateway
and 2 workers).  What is throwing me is I'm only seeing *Cache Hit/Miss*
and *Vizql Bootstrap* data for *only* one of my PRD worker servers; there
is no *Cache Hit/Miss* or *Vizql Bootstrap* data for the 2 DEV workers or
the second PRD worker.

I have been using Java Mission Control and can make a connection to one of
the *Vizql* processes running on the 1 PRD worker that is providing data,
but attempting to connect to a *Vizql* process on any of the other servers
fails with the following error:

Could not connect to <server>:9400. Make sure the JVM is running and that
you are using the correct protocol in the Service URL
(service:jmx:rmi:///jndi/rmi://<server>:9400/jmxrmi).
java.net.ConnectException:
Connection timed out: connectCould not connect to <server>:9401 :
Connection refused to host: <ip address>; nested exception is:
java.net.ConnectException: Connection timed out: connect
Could not connect to <server>:9404. Make sure the JVM is running and that
you are using the correct protocol in the Service URL
(service:jmx:rmi:///jndi/rmi://<server>:9400/jmxrmi).

I've confirmed the listening ports via NETSTAT and I have Vizqlserver
proceses running on 9400-9403

Not sure where to look next.

Jody

-----------------------------------------------------------------------------------------------------------------------------

**Comment by danjrahm** [comment]
Hello Jody,

When trying to connect the the JMX counters were you connecting from the host running TabMon or the separate Tableau Server hosts?

If you were remotely attempting to connect to the JMX counters can you jump onto the Tableau Server hosts and attempt to connect using localhost? This should pull the firewall out of the mix for now. 

Once this test is run please send me the results.

-Dan

**Comment by jody-bossle** [comment]
Dan,

Go ahead and close this.  We have something odd going on between our servers and need to root it out.  All servers can connect to the ports on themselves.  From 2 of my servers I can connect to all 4 servers, but others can only see the JMX ports on the one; although we can TELNET/connect to the ports on all 4.  Not sure what is going on, but I’ll figure it out.

Thanks

Jody

**Comment by danjrahm** [comment]
Closing this.
