### ISSUE TITLE
No data on concurrent users and Vizql Bootstrap activity

### ISSUE THREAD

**Issue by huyingchun** [tableau/TabMon#147]
Hi,

Tabmon is running fine and it can capture server performance data. 
I noticed a few sections of the dashboards are blank.     I thought that navigating within a workbook was considered a ‘bootstrap activity’ and we saw a lot of that in the Tableau logs.  Do you know if we are missing anything here?  I checked the TabMon workbook and it looks like the data columns the worksheet references are all null.  Not sure if something is missing in the setup.

**Comment by huyingchun** [comment]
Thanks Justin for quick response.

We are running Tableau server 10.3. The sample Workbook is for 9.3~10.0. The counters.config file is attached.

Thank you again!
Lily

**Comment by danjrahm** [comment]
Hey @huyingchun,

It looks like the attachment didn't make it to us. Can you attach it directly to this github thread?

Thanks,
Dan

**Comment by huyingchun** [comment]
[Counters_config.txt](https://github.com/tableau/TabMon/files/1412568/Counters_config.txt)
File is renamed to .txt and attached here.

**Comment by danjrahm** [comment]
Hey @huyingchun,

It looks like the issue is that the config file being used to pull counters is for Tableau Server versions 9.3 and 10.

In order for everything to work properly, you will need to replace the current config file with the 10.3 config. This can be found here:
<TABMON ROOT>\Resources\Configurations\10.2+

To apply the changes, please stop tabmon, replace the old config file with the new file, and start tabmon.

Let me know if you have any other questions.

Thanks,
Dan

**Comment by huyingchun** [comment]
Thanks Dan. I have updated the counters.config file. Still the report shows empty. Is it because that the server doesn't have bootstrap activity at all? 
Another question is for concurrent users. There is -2 reached at active sessions. What's that mean?
![active session](https://user-images.githubusercontent.com/32801662/31974212-4557ad98-b8f8-11e7-8bcd-6395d4d4537c.PNG)

**Comment by huyingchun** [comment]
Hi Danjrahm,

Thanks for your help! I check today morning, I can see the data on Bootstrap report. It is great! I think TabMon needs some time to collect the data. 
On the concurrent user report, what's negative number present for?

Thanks,
Lily

**Comment by danjrahm** [comment]
Hi Lily,

I'm glad you are seeing bootstrap activity now. I'm going to move the concurrent users question to another issue for better tracking.

-Dan

**Comment by danjrahm** [comment]
Migrated second question to issue #149.
