### ISSUE TITLE
feature required: password encrytion

### ISSUE THREAD

**Issue by huyingchun** [tableau/TabMon#148]
Hi,

As company's security standard, it doesn't allow clear text password in configuration file. Any suggestion?

I do appreciated for any help!
Lily

**Comment by slewt** [comment]
Do they allow Microsoft's Encrypted File System? If so, logon to the server as the account running TabMon and encrypt any file containing passwords.

**Comment by huyingchun** [comment]
Thanks Slewt! It is good idea!
