### ISSUE TITLE
Tabmon dashboard only displaying Primary server data

### ISSUE THREAD

**Issue by aelmoun2** [tableau/TabMon#150]
Hi,

We have just installed Tabmon in our clustered tableau environment. But, when pulling the report we only see info about the primary server and not all servers part of the same cluster environment.

Any idea why this is happening?
Thank you

**Comment by rahulmotwani** [comment]
Hi @aelmoun2,

Can you confirm that you have setup TabMon correctly for remote polling as per the instructions outlined here: http://tableau.github.io/TabMon/docs/tabmon_configure#remote-polling-setup? Specifically:

1. Ensure that the “Remote Registry” and “Performance Logs & Alerts” Windows services are running and set to Start Mode: Automatic on all remote machines
2. On the TabMon machine, go to Services and right click and select properties for “TabMon”. Make sure that the account for logon has privileges on the machine you would like to remotely connect to. Specifically, the service account must:
    i. On each server you wish to remotely monitor: have admin permissions or be a member of the 
    “Performance Monitor Users” and “Performance Log Users” domain group
    ii. On the machine where TabMon is installed: have permissions to run as a service and write to 
    the TabMon install directory.

Let us know if you are still seeing issues.

**Comment by aelmoun2** [comment]
Hi rahulmotwani,

Thank you for the tips. I was able to do some changes as you have suggested and was able to display the rest of the servers in the cluster environment. However, even applying the same setting on two of the new ones that we have added recently to our environment they are still not being displayed in the report.
Any ideas please?

Thank you

**Comment by danjrahm** [comment]
Hello @aelmoun2,

Can you post your config file? Let's confirm that this is correct before looking into the workbook.

Thanks,
Dan

**Comment by aelmoun2** [comment]
Hi Danjrahm,

Please below the details from the config file. I noticed that the config file is missing the last two servers of our cluster environment (Server 6 and 7). I am not sure if I should manually add them there.

<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="900"/>
  
  <Clusters>
    <Cluster name="Primary">
      <Host name="Server 1"/>
      <Host name="Server 2"/>
      <Host name="Server 3"/>
      <Host name="Server 4"/>
      <Host name="Server 5"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
	
    
      
      
      
    
  </Database>
</TabMonConfig>


Thank you

**Comment by aelmoun2** [comment]
<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="900"/>
  
  <Clusters>
    <Cluster name="Primary">
      <Host name="Server 1"/>
      <Host name="Server 2"/>
      <Host name="Server 3"/>
      <Host name="Server 4"/>
      <Host name="Server 5"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
	
    
      
      
      
    
  </Database>
</TabMonConfig>

**Comment by aelmoun2** [comment]
Hi Danjrahm,

After adding Server 6 and 7 to the Tabmon config file. I am able to see them in the report but no data is attached to them. 
Any idea?

**Comment by danjrahm** [comment]
Hello,

Before we look further into this issue, have the troubleshooting steps that Rahul mentioned above been applied to server 6 and 7?

If they have and we're still receiving this issue, please send the tabmon log file. The file is located here:
<TABMON ROOT>\Logs\

Thanks,
Dan

**Comment by danjrahm** [comment]
@aelmoun2 The last comment was blank. Were you trying to paste the logs in?

**Comment by aelmoun2** [comment]
Thank you all for your help,
I am able to see all data in the report. Yesterday I wasn't able to view data for server 6 and 7 since they were just added to the config file.

Thanks again for you time.

**Comment by rahulmotwani** [comment]
@aelmoun2 - glad to hear that. I'm going to close this issue out. Feel free to re-open it or open a new one for other errors you encounter.
