### ISSUE TITLE
Tabmon 1.2 - Fails to purge old records

### ISSUE THREAD

**Issue by sqllackey** [tableau/TabMon#151]
We have just installed Tabmon 1.2 after running 1.0 for the past 16 month or so.  We set the purge threshold to 90 days.  Unfortunately, we still have all the records, non are purged.  It seems be a time out error and we look to you for a fix.  Thanks much.

2017-10-27 14:10:10,204 [50] DEBUG DataTableWriter.Adapters.DbAdapter - Dropping rows from table 'countersamples' older than 90 days..
2017-10-27 14:10:30,204 [50] ERROR DataTableWriter.Adapters.DbAdapter - Unable to drop rows from table 'countersamples': ERROR: 57014: canceling statement due to statement timeout
2017-10-27 14:10:30,204 [50] ERROR DataTableWriter.Writers.DataTableDbWriter - Unable to delete rows: ERROR: 57014: canceling statement due to statement timeout

**Comment by sqllackey** [comment]
After the query runs for about 10 -15 minutes I get this.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by sqllackey** [comment]
I am going to try a smaller amount of data to delete and walk it back to 90 days.  I will report back on success/failure.

**Comment by danjrahm** [comment]
Hello, 

It sounds like we're hitting a query timeout. If you continue to hit this, let me know and I'll write a query that allows us to limit the number of rows we try to delete at once.

Thanks,
Dan

**Comment by sqllackey** [comment]
Thanks - I got it down to only 90 days worth (our goal) which accounts for around 50,000,000 rows.  We had over 360,000,000 before the delete statements.  We will need to make note of this when we migrate to our production environment.

**Comment by danjrahm** [comment]
Great, I'm glad this was figured out. If more people run into this issue, I'll put a limit on the number of rows that we attempt to delete at once. This will cut down on the query time and allow TabMon to slowly purge large amounts of data.

I'm going to go ahead and close this.

**Comment by landonconover** [comment]
I have also run into this issue. Everything from above is consistent. I believe the database is timing out when the app tries to delete the data.

I am going to attempt to delete the rows manually.

**Comment by danjrahm** [comment]
Hello,

I am sorry to hear you are running into this issue. I have a proposed solution for this and will address it in the next update.

Thanks,
Dan
