### ISSUE TITLE
TabMon installation

### ISSUE THREAD

**Issue by vinothdakshin** [tableau/TabMon#153]
An error occurred while communicating with postgreSQL Database. 
Unable to connect to the server.Check that the server is running and that you have access privileges to the requested database.

**Comment by danjrahm** [comment]
Is this when running TabMon or connecting to the database manually?

**Comment by vinothdakshin** [comment]
Hi,

Thanks for the reply.

This issue occurred when connecting to the database.

Best Regards,
_____________________________________________________
Vinoth Kumar T

**Comment by danjrahm** [comment]
Are you connecting to the database via Tableau or a console application (e.g. PGAdminIII)? This may be due to permissions set in the pg_hba.conf file. 

https://www.postgresql.org/docs/9.3/static/auth-pg-hba-conf.html

Are you connecting via local host or a remote computer?

-Dan

**Comment by vinothdakshin** [comment]
Hi ,

Apologies for the delayed response.

We are trying the connect the database via Tableau.

Kindly confirm whether Tabmon1.1 will support Tableau server 10.x version.

Best Regards,
_____________________________________________________
Vinoth Kumar T

**Comment by danjrahm** [comment]
TabMon 1.1 outputs a datasource that is compatible with all versions of Tableau Desktop.

Does TabMon properly write samples to the postgres database? Also, is this the postgres instance that is included with TabMon or a separate instance that was manually setup?

**Comment by vinothdakshin** [comment]
Hi  Dan,

Thanks for the response.

May I know how do I ensure whether TabMon properly writing the samples to postgres?

We have installed separate PostgresV10 instance.


Best Regards,
_____________________________________________________
Vinoth Kumar T

**Comment by danjrahm** [comment]
The best method would be through the TabMon log files. They can be found in the TabMon\Logs folder. If everything is running correctly you should not see any errors in the log files.

You can also verify that it is working by looking for a TabMon database and countersamples table within postgres. 


As for the issue with not being able to connect to postgres. You may need to edit the postgres pg_hba.conf file. Here is some documentation on editing the file: https://www.postgresql.org/docs/9.1/static/auth-pg-hba-conf.html

Let me know if there are any other questions.

-Dan

**Comment by danjrahm** [comment]
Hello,

Since there hasn't been activity on this thread I am closing it out.

Thanks,
Dan
