### ISSUE TITLE
Unable to start tabmon service when adding the primary server to the configuration

### ISSUE THREAD

**Issue by OmkarLakhe** [tableau/TabMon#155]
@danjrahm and Team,

I have installed and configured tabmon on my secondary server and it working fine when i just specify the localhost as in the secondary instance to the tabmon configuration file.
As soon as i add the primary instance in the cluster settings the tabmon services stops responding and doesnt start. 
I have checked all the previously raised issues. 
The remote Registry service is also running on the primary server. 
PFB the error message. 
Windows could not start the TabMon service on Local Computer.
Error 5: Access denied.

Tabmon log :
2017-11-02 11:31:22,675 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2017-11-02 11:31:22,699 [5] INFO TabMon.Config.TabMonConfigReader - Initializing CSV writer..
2017-11-02 11:31:22,707 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'tab-server-win2' to 'tab-server-win2'.
2017-11-02 11:31:22,708 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'tab-server-win1' to 'tab-server-win1'.
2017-11-02 11:31:22,712 [5] INFO TabMon.Config.TabMonConfigReader - Successfully loaded TabMon config options! [Hosts='Secondary\tab-server-win2,Primary\tab-server-win1', Writer='CSV File Writer', PollInterval='60', TableName='countersamples']
2017-11-02 11:31:22,712 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2017-11-02 11:31:22,714 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading persistent performance counters from C:\Program Files (x86)\TabMon\Config\Counters.config..
2017-11-02 11:31:22,717 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading performance counters from C:\Program Files (x86)\TabMon\Config\Counters.config..
2017-11-02 11:31:22,721 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Successfully validated 'Config\Counters.config' against 'Resources\CountersConfig.xsd'.
2017-11-02 11:31:22,721 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loading Perfmon counters..
2017-11-02 11:31:23,012 [5] DEBUG TabMon.CounterConfig.CounterConfigLoader - Loaded 86 persistent Perfmon counters on tab-server-win2.
2017-11-02 11:32:05,015 [5] ERROR TabMon.TabMonAgent - Failed to initialize counter sampler using counters from configuration file: The network path was not found.

Aborting..
2017-11-02 11:32:05,015 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2017-11-02 11:32:05,020 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

Tabmon Config:
<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="CSV"/>
  
  <PollInterval value="60"/>
  
  <Clusters>
    <Cluster name="Secondary">
      <Host name="tab-server-win2"/>
    </Cluster>
	<Cluster name="Primary">
      <Host name="tab-server-win1"/>
    </Cluster>
  </Clusters>
  
  <Database name="tabmon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="pasword"/>
    <Table name="countersamples"/>
    
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    
    <PurgeOldData enabled="false" thresholdDays="30"/>
  </Database>
</TabMonConfig>

#30

**Comment by danjrahm** [comment]
What version of TabMon is this? It may be that the computer name or address is not resolving.

**Comment by OmkarLakhe** [comment]
Hi @danjrahm 

I am currently using 1.2 version of tabmon. I am able to connect to the primary server now after i gave the complete computer name but it is not capturing any perfmon counters. It is showing zero records in the csv file. 
PFB the error message.

2017-11-03 09:45:04,183 [8] ERROR TabMon.CounterConfig.PerfmonCounterConfigReader - Unable to load PerfMon counters for host Primary\10.x.xx.xxx\tab-server-win1.ant.domain.com: The network path was not found.

Kindly let me know in case of any more information required.

**Comment by danjrahm** [comment]
As an initial troubleshooting step, let's remove nodes, other than the primary, from the TabMon config file. Once this is done, please start TabMon and confirm that it works properly.

As long as TabMon is working properly, I would attempt to add the other nodes one at a time. It's likely that computer name and address are not set properly.

Here are the steps needed to gather the information required to configure TabMon:

To set these fields we will need 2 pieces of information the Tableau Server host's computer name and FQDN or IP address.

To find the hostname, please refer to section 2 of the FAQ.

To find the FQDN just add the domain to the end of the computer name.

To find the ip address open a command prompt on the Tableau Server machine and type "ipconfig". The ip address should be after "IPv4 Address".

Once the computer name and FQDN/IP Address are collected, please enter the computer name into the "computerName" attribute of host and the FQDN/IP Address into the address.

**Comment by OmkarLakhe** [comment]
Hi @danjrahm ,

I have already followed the above mentioned steps and also kept the FQDN name. Please find below the config file. 

<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="csv"/>
  
  <PollInterval value="60"/>
  
  <Clusters>
    <Cluster name="Primary">
      <Host computerName="tab-server-win1.xxx.xxxxx.com" address="xx.1.xx.xxx"/>
    </Cluster>
	 <Cluster name="Secondary">
      <Host computerName="tab-server-win2.xxx.xxxxx.com" address="xx.1.xx.xxx"/>
    </Cluster>
  </Clusters>
  
  <Database name="tabmon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
    
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    
    <PurgeOldData enabled="false" thresholdDays="30"/>
  </Database>
</TabMonConfig>


THe error that i am getting in the log file is as below: 

2017-11-07 08:51:03,474 [3] ERROR TabMon.CounterConfig.PerfmonCounterConfigReader - Unable to load PerfMon counters for host Primary\xx.1.xx.xxx\tab-server-win1.xxx.xxxxx.com: The network path was not found.

If you see the config file i have added the secondary server and it is working file. It is capturing all the performance metrics. 

Regards,
Omkar Lakhe

**Comment by OmkarLakhe** [comment]
Hi @danjrahm ,

Any update on the same. need it on urgent bases. 

Thanks in Advance. 
Omkar Lakhe

**Comment by danjrahm** [comment]
Hello,

The config wasn't included. Can you attach it to a comment as a text file?

Thanks,
Dan

**Comment by OmkarLakhe** [comment]
[tabmon.config.txt](https://github.com/tableau/TabMon/files/1474172/tabmon.config.txt)

**Comment by OmkarLakhe** [comment]
Hi @danjrahm 
I have attached the config file in comment. 
Kindly let me know in case you need any more info.

Regards,
Omkar Lakhe

**Comment by danjrahm** [comment]
I have a couple questions about the config and environment.

1. Are the computer names tab-server-win1 and tab-server-win2? These entries should not be FQDN's but just the plain computer name.
2. Are these two computers part of the same cluster or completely separate servers?
3. Are these computers in the same subnet?

-Dan

**Comment by OmkarLakhe** [comment]
Hi @danjrahm ,

Please find below my comments : 
1. I have made the  changes as suggested removed the domain information from the computer name. -- Issue still persists (unable to connect to primary from secondary)
2. These two machines are two different EC2 instance on AWS. We are able to ping from one server to another 
3. yes

Even after making the changes as suggested i am not able to gather information for the primary server when i am running the tabmon from the secondary server.

Regards,
Omkar

**Comment by danjrahm** [comment]
The error you are receiving occurs when the computer name is incorrect or cannot be looked up. This may be a limitation with remotely running perfmon remotely on EC2.

To see if we can remotely poll perfmon counters please perform the test below:

1. Log into the secondary server.
2. Open perfmon.exe
3. In the left pane, drop down the 'Monitoring Tools', and select 'Performance Monitor'.
4. In the new (right) pane, select the green 'plus' icon.
5. Under 'Select counters from computer:' select the 'Browse...' button.
6. In the new menu, enter the hostname of the primary server without the domain.
7. Once done, select 'Check Names'.

If this works properly, you should see the hostname underlined and be able to select 'OK'. If it doesn't work, you should see a warning that looks like this:

![hostnameerror](https://user-images.githubusercontent.com/5581233/33102587-516f628e-ced2-11e7-9b40-a2670a30bf50.PNG)

If this warning appears it means that Perfmon cannot look up the host and poll the data. In this case we may be able to work around the limitation by changing the hosts file, but we'll get to that after the test.

**Comment by OmkarLakhe** [comment]
Hi @danjrahm ,
I followed the steps mentioned above and i did get the above pop up when i did the check names. 
So i guess we are not able to pull data from the primary to the secondary. 
Do let me know the work around for this.

Regards,
Omkar Lakhe

**Comment by danjrahm** [comment]
Hello,

As long as the primary has a static IP address you should be able to add it to the hosts file on computer running TabMon.

The entry would look something like this:
xx.1.xx.xxx  tab-server-win1

This article has some good info on changing the entries in the hosts file:

**Comment by OmkarLakhe** [comment]
Hi @danjrahm 

I have made the changes in the host file on the secondary server. But still when i check the results folder I couldn't see the primary host information getting populated. 
The fix didn't work. :( :-( 
Can you please help me with the same.

Regards,
Omkar Lakhe

**Comment by OmkarLakhe** [comment]
Hey @danjrahm ,

Even after adding the host information in the host file when i perform the same task 
To see if we can remotely poll perfmon counters please perform the test below:

    Log into the secondary server.
    Open perfmon.exe
    In the left pane, drop down the 'Monitoring Tools', and select 'Performance Monitor'.
    In the new (right) pane, select the green 'plus' icon.
    Under 'Select counters from computer:' select the 'Browse...' button.
    In the new menu, enter the hostname of the primary server without the domain.
    Once done, select 'Check Names'.

I still get the same error pop up. 
that means even after adding in the host file the perfmon is not able to see the server.

kindly let me know your thoughts on the same.

Regards,
Omkar Lakhe

**Comment by danjrahm** [comment]
Hello Omkar,

Sorry for the delayed response.

Since my recommended workaround didn't work, I'm not sure that there is anything else that I can do. You may need to work with your network team to see why you are unable to remotely poll perfmon counters.

At this point, this issue looks like a network configuration issue rather than a TabMon issue.

Let me know if you have any other TabMon questions.
-Dan

**Comment by danjrahm** [comment]
Hello,

I am going to close this out. If you need any further assistance let me know. 

Thanks,
Dan
