### ISSUE TITLE
Blank Worksheets

### ISSUE THREAD

**Issue by ulakhanpal** [tableau/TabMon#156]
I have TabMon running on the server alongside Tableau Server. I'm trying to view the sample workbook.

Most of the sheets in the sample workbook are showing as blank. I've left the config file largely untouched (aside from changing the COMPUTERNAME to the servers hostname).

The only sheet with any data on it is "Cache Hit/Miss Analysis" and the "Logins Per Hour" section of "Concurrent Users".

Would you know what further reading I may be missing to configure this correctly?

**Comment by rahulmotwani** [comment]
Hi @ulakhanpal,

When you set up TabMon, did you set it to use the Counters.config file and Sample Workbook versions that match your version of Tableau Server? These are found in the "Resources" folder within the TabMon install directory. What version of Tableau Server are you using?

**Comment by ulakhanpal** [comment]
Hey @rahulmotwani,

I believe so. It's Tableau Server 10.3, I'm using the sample workbook from the 9.3-10.2+ folder. 

Ah! I was using the incorrect Counters.config file, I'd assumed the default was already set for Tableau Server 10.2+. The sheets are are showing data now. Thanks for your help!

**Comment by rahulmotwani** [comment]
@ulakhanpal - glad to here you were able to resolve this issue yourself! 👍
