### ISSUE TITLE
Unable to load PerfMon counters for host

### ISSUE THREAD

**Issue by BFASEricP** [tableau/TabMon#157]
I have installed TabMon on a separate server from our Tableau Server. When the primary host is set to the TabMon server itself it works just fine, When I change the primary host to the Tableau Server I get errors.

`2017-11-17 16:39:15,003 [5] ERROR TabMon.CounterConfig.PerfmonCounterConfigReader - Unable to load PerfMon counters for host Primary\tbldevapp02.<domainname>\TBLDEVAPP02: The network path was not found.`
`Please verify that the computer name is configured correctly.`

I have also tried using the IP in the address attribute with the same result. Both servers are in the same domain.

**Comment by BFASEricP** [comment]
I have also found this message from PostgreSQL in Event Viewer that could be related.
`LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.`

**Comment by danjrahm** [comment]
Can you confirm that “Remote Registry” and “Performance Logs & Alerts” Windows services are running on the Tableau Server machine(s)?

**Comment by OmkarLakhe** [comment]
Hi @BFASEricP 

Even i am getting the same error. https://github.com/tableau/TabMon/issues/155
and my primary and secondary both have remote registry and performance logs and alters services running.

Regards,
Omkar Lakhe

**Comment by BFASEricP** [comment]
Yes, the Tableau Server did have those both running. Although I did have to start the "Remote Registry" service myself. Its startup type is set at "Automatic (Triggered Start).

**Comment by danjrahm** [comment]
@BFASEricP 

Is the Postgres DB you're using for tabmon installed manually or is it the DB included with Tabmon?

**Comment by danjrahm** [comment]
Based on the error above,

`2017-11-17 16:39:15,003 [5] ERROR TabMon.CounterConfig.PerfmonCounterConfigReader - Unable to load PerfMon counters for host Primary\tbldevapp02.<domainname>\TBLDEVAPP02: The network path was not found.
Please verify that the computer name is configured correctly.`

it looks like the computer name is incorrect. When on the primary node of Tableau Server, if you open the command prompt and type "hostname" does it return "TBLDEVAPP02"?

**Comment by BFASEricP** [comment]
Yes, I get TBLDEVAPP02. I can also ping it by both hostname and fqdn.

**Comment by BFASEricP** [comment]
The PostgreSQL db is the one set up by the TabMon installation.

**Comment by danjrahm** [comment]
This is likely similar to issue #155. 

Can you attach your tabmon config (please 'x' out all sensitive data) to this thread. Be sure it's a text file and not pasted text.

Also, can you confirm that the hostname, ip address, and FQDN are all correct for host  TBLDEVAPP02?

Also, are these hosts in the same subnet?

Thanks,
Dan

**Comment by BFASEricP** [comment]
I have checked that the hostname, IP address, and FQDN are correct for TBLDEVAPP02. The attached config file uses the hostname for the computerName attribute but I have also tried the IP address. The Tableau (TBLDEVAPP02) and TabMon (TBLTSTAPP01) servers are on the same domain but different subnets, 10.1.x.x for TBLTSTAPP01 and 10.20.x.x for TBLDEVAPP02. I tried remotely connecting from TBLTSTAPP01 to TBLDEVAPP02 with Perfmon and it didn't work. I have turned off the firewall on TBLDEVAPP02 but suspect there might be something going on with network security. Do you know what ports I should check?

[TabMon.config.txt](https://github.com/tableau/TabMon/files/1519607/TabMon.config.txt)

**Comment by danjrahm** [comment]
If Perfmon cannot manually be resolved, TabMon will not be able to pull the perfmon counters.

This article has some good information on troubleshooting perfmon:
https://www.logicmonitor.com/support/monitoring/os-virtualization/troubleshooting-perfmon-access/

If this doesn't work, the hosts file workaround I mentioned in issue #155 may work.

**Comment by BFASEricP** [comment]
I have solved this problem. Working with our system and security administrators we tracked it down to setting the Security Group configuration (we are on AWS) to allow the Perfmon and Java Management Extensions ports.

**Comment by danjrahm** [comment]
That's great. I'm glad you were able to get this working! I'm closing this out now.
