### ISSUE TITLE
How do i connect TabMon with Tableau server?

### ISSUE THREAD

**Issue by naveentalari** [tableau/TabMon#169]
Hi All,

Recently i have installed TabMon to monitor my server performance.

by clicking the sample workbook in  resources folder, i'm able to open tabmon using tableau desktop, that's ok, but i don't know what metrics tabmon is giving on the startup page.

it asked me postgre db password and server audit password, i am connected with it, anyway i can able to see some performance metrics, i really don't know is that my Tab server performance metrics?

i am little confused on using tabmon, my intention is to monitor my server performance(cpu, memory, no of concurrent users, etc), but i haven't seen those metrics really compatible to my server.

Please help me out on this, i really wanna do this to test my server performance.

it would be great if you provide me step by step analysis to get connected with server and to monitor the server performance using TabMon.

Thanks,
Naveen

**Comment by danjrahm** [comment]
Hello,

My understanding is that you are attempting to monitor your Tableau Server instance with TabMon but not all counters are being polled. Is this correct?

Before we continue, have you followed all of the steps in the [TabMon setup guide](https://tableau.github.io/TabMon/)?

Also, are you using the correct counters config and workbook for your version of Tableau Server?

Thanks,
Dan

**Comment by naveentalari** [comment]
Hi Dan,

Thanks for your prompt reply.

Yes, I followed steps from the setup guide.

Steps:
1. Enabled JMX ports to tableau server from cmd line.
2.Setup Read only user.
3.Installed TabMon
4.Configured Config file by changing my server name, as well as address.
5.Opened Sample workbook 9.5 or above.
6.Given password for postgre and server auditing.
7.Workbook opened and started showing results.
8.CPU, Memory, Disk etc.

But i don't know which counters it's showing, very confused about this, also i didn't seen any  active session running  and Concurrent  login users page is blank.
![tabmon2](https://user-images.githubusercontent.com/36216722/36238303-b6fd35de-1227-11e8-8e53-fd7ad779b66d.png)

Also, Vizql Page is totally blank
![tabmon1](https://user-images.githubusercontent.com/36216722/36238291-b16bd206-1227-11e8-86b9-f0ec1703ab87.png)

Also, attaching my log file for your reference.
[TabMon.log.txt](https://github.com/tableau/TabMon/files/1726272/TabMon.log.txt)

Please help me with this, we are going to use this to monitor production tableau server.

Thanks,
Naveen

**Comment by danjrahm** [comment]
Hello Naveen,

What version of Tableau Server are you trying to monitor? How active is the server that is being monitored?

Also, can you attach the TabMon log files? They should be found here:
C:\Program Files (x86)\TabMon\Logs\TabMon.log

Thanks,
Dan

**Comment by naveentalari** [comment]
Hello Dan,

I'm using Tableau 10.4 Version, The server is going to be Production in few days.

i also monitors Tableau server status page, which gives each and every metrics what happing inside server(Traffic of Views, Space Status, Logins per second, Memory Etc).

I'm really confused that TabMon counters are not matching to tableau server status metrics.

Please help me, As you said i am attaching Log file here(Due to security reasons i have grayed out Tableau server URL in log file).

[TabMon.log.txt](https://github.com/tableau/TabMon/files/1735784/TabMon.log.txt)

Kindly help me :-) 

Thanks,
Naveen

**Comment by naveentalari** [comment]
Dan,

One more request, what about Time stamp?
how do we set up time stamp to pull  counters?
i can see some counters but i can't see present running counters in server.
i tired to change time stamp(date and time), but i haven't seen any changes in counters.
how can we set TabMon to pull counters lively, why was time stamp not changing?

Please help me with above all.

Thanks
Naveen

**Comment by danjrahm** [comment]
Hello, 

Based on the logs it looks like JMX counters are not enabled on Tableau Server. To enable this, please follow the steps in the 'Configure Tableau Server' portion of the [TabMon Setup Guide](https://tableau.github.io/TabMon/docs/tabmon_prereqs). Once this setting is implemented, restart TabMon.

Performing the steps above should allow TabMon to collect the necessary JMX data.

As far as the timestamp bit goes, I am not sure what you mean by 'set up time stamp to pull counters'. The poll rate is based off of the setting in the TabMon config and the timestamp used for polling is based off of the host time. The workbook should pick this up automatically but if the old workbook is being used the time offset may need to be used.

Thanks,
Dan

**Comment by naveentalari** [comment]
Hi Dan,

I'm sure that i enabled JMX Counters before installing TabMon, anyway with your advice i will do it again.

Also, i can't able to see counters after Feb 15th 

![untitledd](https://user-images.githubusercontent.com/36216722/36517004-892c2690-17a6-11e8-89e3-dede2af5a9f8.png)

Please check above screenshot, mean while i will follow your advice and come back to you.

Thanks,
Naveen

**Comment by naveentalari** [comment]
Hi Dan,

i have set up JMX again to my tableau server.

After i made TabMon Restart, i have not seen any changes the page displays like same as previous.

Your help is much appreciated.

Thanks,
Naveen

**Comment by danjrahm** [comment]
Hello Naveen,

Can you attach the TabMon logs for that period? Also, what version of the workbook and Counters config are you using. There is the possibility that this is a version mismatch.

Thanks,
Dan

**Comment by danjrahm** [comment]
Hello Naveen,

Due to thread inactivity I am going to close this. Please let me know if you are still running into the same issues.

Thanks,
Dan
