### ISSUE TITLE
TabMon not polling data from one node

### ISSUE THREAD

**Issue by michaelperillo** [tableau/TabMon#171]
TabMon is not able to retrieve data from one of my servers from my Production environment (specifically my worker 02 as shown below.  The node is configured, OS-wise, exactly the same as all the others (Remote Registry and PLA is running).  Any ideas on what to try and test to see what's wrong?

I have my TabMon.config file as such:

<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="60"/>
  
  <Clusters>
    <Cluster name="Production">
      <Host computerName="PROD-PRIMARY" address="10.0.0.5"/>
	  <Host computerName="PROD-WORKER01" address="10.0.0.6"/>
	  <Host computerName="PROD-WORKER02" address="10.0.0.4"/>
    </Cluster>
	<Cluster name="Development">
      <Host computerName="DEV-PRIMARY" address="10.0.0.1"/>
	  <Host computerName="DEV-WORKER01" address="10.0.0.2"/>
	  <Host computerName="DEV-WORKER02" address="10.0.0.3"/>
    </Cluster>
	<Cluster name="Sandbox">
      <Host computerName="SB-PRIMARY" address="10.0.0.14"/>
	  <Host computerName="SB-WORKER01" address="10.0.0.15"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="USER" password="PASS"/>
    <Table name="countersamples"/>
    
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    
    <PurgeOldData enabled="true" thresholdDays="30"/>
  </Database>
</TabMonConfig>

**Comment by michaelperillo** [comment]
UPDATE: 2018-02-20 2:25pm MST

- I modified the entry for the worker node replacing the hostname with the ip address as such
	  _<Host computerName="10.0.0.4" address="10.0.0.4"/>_
- I saved the TabMon.config file, and restarted the TabMon Service (running on a separate machine)
- Data started flowing into TabMon after a bit (verified by looking at the various reports in the TabMon sample workbook)
- I changed the TabMon config entry back to use the hostname of the server, making sure I copy/pasted the hostname exact (at command prompt running hostname <enter> on the box), saved the file and and restarted the TabMon service
- Data not coming through when the worker's computername is used. 

So odd... I don't really have a problem using the IP Address as the ComputerName (I can alias it in TabMon workbook). But I'd like to understand what's going on.  

The production platform is all on the same network, same subnet, same firewall config.

**Comment by michaelperillo** [comment]
UPDATE: 2018-02-21 9:15am MST

- From the server with TabMon installed, I opened perfmon (perform.exe) and attempted to connect  to another computer (Perfmon > Action > Connect to another computer...)
- I entered the IP Addresses of the Production Servers and connected fine
- I entered the ComputerName of the server of each production server and received Access Denied (Interesting)
- This made it clear to me what the issue was (the computer name wasn't being recognized because the servers were part of a different domain than all my other environments. And it's obvious because I have my list of servers with the domains they belong to right next to me.  
- So, I use the computername + domain (e.g. PROD-PRIMARY.domainname.com) and I can connect to perfmon via the remote computer
- I adjusted the TabMon.config to include the hostname FQDN, save the file and restart the TabMon.config file
- WHAT A DIFFERENCE!! I was getting data

*********************************** SUGGESTION *********************************************
While this should have been apparent from the beginning, I would suggest adding in the Getting Started/Installation instructions that users can use the Hostname for ComputerName if their company domain only has one domain. Otherwise using the FQDN of the servername is preferred when working with different domains (despite being trusted).

**Comment by danjrahm** [comment]
Hello Michael,

Sorry for the delay in my response. I am happy to see that everything is now working for you! I have labeled this issue a 'suggestion'. This way I'll be able to address the suggestion next time I update TabMon.

Thanks again for the suggestion! If you have any other questions let me know.
-Dan

**Comment by danjrahm** [comment]
Hello, 

A note has been added to the '[Configuring TabMon](https://tableau.github.io/TabMon/docs/tabmon_configure)' section of our guide. I am now going to close this suggestion.

Thanks,
Dan

**Comment by michaelperillo** [comment]
Thanks, Dan!!

**Comment by danjrahm** [comment]
No problem!
