### ISSUE TITLE
Problem connecting to the data source "TabMon"

### ISSUE THREAD

**Issue by amitrajpal89** [tableau/TabMon#173]
Hello Team,

I have installed the TabMon on the server. However, when I open the workbook and enter the password it throws below error.

ERROR: relation "public.countersamples" does not exist; Error while executing the query
The table "[public].[countersamples]" does not exist.
Unable to connect to the server "localhost". Check that the server is running and that you have access privileges to the requested database.

Please could you help resolving the same. Let us know if any other information is required.

Thanks,
Amit Rajpal

**Comment by amitrajpal89** [comment]
Hello Team,

Adding the information regarding the steps followed:

While Installation Install and initialie Postgres for me. (Recommended) was checked.

Configured Tabmon.config as per the instructions given in the below url.
https://tableau.github.io/TabMon/docs/tabmon_configure

Ensured that the "Remote Regisry" and "Performance Logs & Alerts" Windows services were running and set to Start Mode: Automatic on all remote machines.

Ensured that account for logon has privileges on the machine I would like to remotely connect to.
Service account have admin permissions or be a member of the "Administrators", “Performance Monitor Users” and “Performance Log Users” domain group
On the machine where TabMon is installed services account have permissions to run as a service and write to the TabMon install directory.

Started the service using "StartTabMonService" Windows Batch File by righclicking on it and selecting "Run as Administrator".

Opened the workbook from Folder Resources -> Sample Workbooks -> 9.3 - 10.2+

On the target server, Tableau server is installed on version 10.5.1.

Please let me know if I have missed out on any steps.

Thanks,
Amit Rajpal

**Comment by danjrahm** [comment]
Hello Amit,

Can you send me the TabMon logs? The table should be created the first time TabMon is run. If there is an issue creating the table, the logs will offer more information.

The logs can be found here: <ROOT>\TabMon\Logs\TabMon.log.txt

Once I receive the logs I should have a better idea as to what's happening.

Thanks,
Dan

**Comment by danjrahm** [comment]
Hello Amit,

Due to thread inactivity I am going to close this. If the issue still persists please let me know.

Thanks,
Dan

**Comment by ankunil** [comment]
I am also facing same issue please help me
