### ISSUE TITLE
Linux support for Tableau Linux workers

### ISSUE THREAD

**Issue by tfoldi** [tableau/TabMon#18]
How do you guys plan to support Linux Workers? As I understood Tableau Server on Linux is pretty close to public release and I am wondering how the current code base would work on linux. 

Like how it compiles with mono

**Comment by jmangue** [comment]
Hi tfoldi, unfortunately I'm not at liberty to discuss any plans to release Server for Linux.. all I can say is that right now, TabMon is pretty tightly coupled to Windows and potentially updating it to include Linux support would be possible, but would be a major overhaul.

Closing this issue as currently out of scope.
