### ISSUE TITLE
Unable to start Tabmon

### ISSUE THREAD

**Issue by Tabuser** [tableau/TabMon#184]
Hi,

We have a clustered env. I installed the tabmon on a separate machine to connect to this cluster. The installation was successful but its not starting because of the following error

FATAL TabMon.Config.TabMonConfigReader - Error loading TabMon.config: Unrecognized attribute 'name'. Note that attribute names are case-sensitive. (D:\Tabmon\Config\TabMon.config line 11))
2018-07-23 18:49:37,477 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully.
The 11th line is where we have the <hostname>="server1" as shown below

<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="5"/>
  
  <Clusters>
    <Cluster name="Primary">
      <Host name="server1"/>
      <Host name="server2"/>
      <Host name="server3"/>
      <Host name="server4"/>
      <Host name="server5"/>
      <Host name="server6"/>
      <Host name="server7"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
    
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    
    <PurgeOldData enabled="true" thresholdDays="30"/>
  </Database>
</TabMonConfig>

I also tried as below where
<Host name="server1" address="server1"/>
<Host name="server2" address="server2"/>
--
--
--
<Host name="server7" address="server7"/>

It was not successfully. Any help is appreciated.

Thanks

**Comment by Tabuser** [comment]
[TabMon.log.txt](https://github.com/tableau/TabMon/files/2221399/TabMon.log.txt)
 
Attached is the logfile for ref.

**Comment by danjrahm** [comment]
Hello,

Is it possible to share your TabMon config file? Feel free to obfuscate any sensitive data. I should be able to tell what's happening by looking into the config file.

Thanks,
Dan

**Comment by SamanthaGun** [comment]
Hi Dan
Has this been resolved? I am getting the same error in the log file when trying to connect to the Tableau server remotely. TabMon.config file is given below. 11th line is where the host IP is mentioned. User account that I am using has remote access to the Tableau server (with admin rights).

<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="60"/>
  
  <Clusters>
   <Cluster name="Tableau Prod">
      <Host name="99.99.99.99"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="9999"/>
    <Table name="countersamples"/>
    
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    
    <PurgeOldData enabled="false" thresholdDays="30"/>
  </Database>
</TabMonConfig>

**Comment by danjrahm** [comment]
Hello @SamanthaGun,

Sorry for the delay in response. Can you open another issue and post your TabMon.config there along with the logs while trying to start TabMon? I'll dig into it in that issue.

Thanks for the help.
Dan

**Comment by danjrahm** [comment]
Hello @Tabuser,

Due to inactivity on this I am going to close this issue. If this is still occurring please let me know.

Thanks,
Dan
