### ISSUE TITLE
TabMon for version 2018.1

### ISSUE THREAD

**Issue by SJTison** [tableau/TabMon#185]
I have installed TabMon 1.2 on tableau 2018.1 and it is running fine BUT no figures for Concurrent Users.
I have tried all the things suggested in other threads.
Do you know how to get this working ?

**Comment by mattdotgreenlake** [comment]
Since you have singled out one sheet, I presume the TabMon postgres connection is otherwise working and populating data on the other sheets.
Try removing filters on that sheet to see if data starts appearing.
Otherwise try to rebuild the sheets in that dashboard to see if some field has nulls.  If it does perhaps you need to review the counters config to make sure nothing was incidentally removed or modified.

**Comment by yapnel** [comment]
I am running 2018.2 and also facing the same and did observe jmx port scanning stop. PerfMon counters are coming back fine but not jmx. Kindly please advise. Thanks

**Comment by mattdotgreenlake** [comment]
What I've found is that the ports are assigned randomly now in 2018.2 (perhaps 2018.1 as well)
So while 10.5 would assign jmx ports for vizql starting at 9400 and assign serial ports for all jmx counters, 2018.x randomly assigns ports in the range from 8000-9000.  see https://onlinehelp.tableau.com/current/server/en-us/ports.htm

So tabmon starts looking at port 9400 for vizql, sees nothing and dies.
We can either set tabmon to scan a lot of ports, testing each to know if it's a jmx counter...not sure this is efficient, or we can use the *tsm topology set-ports* to manually put these ports back where the tabmon config expects them to be.  
I'm still looking for an easier way to do this.

**Comment by mattdotgreenlake** [comment]
Some news.
**At install** you can use the configuration options here to modify all the ports you want at one time using a json file as described `[here](https://onlinehelp.tableau.com/current/server/en-us/ports.htm)`.
You would use this method to set the ports to match what is expected per the tabmon config.

If you are catching this post-install, the story gets a little tougher.  You have to change each port, one at a time and each change requires a restart.  I count about 17 restarts.  That is far from ideal and I'm chasing this up inside Tableau.  Also the documentation, as of writing this note, isn't correct.  To change ports with tsm, this is the syntax I've found to work:

tsm topology set-ports -n node1 --port-name vizqlserver:jmx -pv 9400 -i 0
tsm topology set-ports -n node1 --port-name vizqlserver:jmx.rmi -pv 9401 -i 0
tsm topology set-ports -n node1 --port-name vizqlserver:jmx -pv 9402 -i 1
tsm topology set-ports -n node1 --port-name vizqlserver:jmx.rmi -pv 9403 -i 1
tsm topology set-ports -n node1 --port-name vizqlserver:jmx -pv 9404 -i 2
tsm topology set-ports -n node1 --port-name vizqlserver:jmx.rmi -pv 9405 -i 2

hopefully these patterns will help you update your ports to match the expected port ranges in the tabmon config.  I'm going to chase up work on our docs and how these port updates work.

**Comment by danjrahm** [comment]
Matt is correct here. With the launch of TSM, JMX ports have been changed. We can find the current ports by running "tsm topology list-ports". I'm going to look a bit further into it this week.

Thanks,
Dan

**Comment by yapnel** [comment]
Any update on this? Tabmon is supposed to be the monitoring tool for Tableau but it is not working properly with the newer version.

**Comment by danjrahm** [comment]
@yapnel 

Quick Update:
2018.1 is working. The workbook has a bug though. I'll look into that.

**Comment by danjrahm** [comment]
Hello,

This issue is fix with [release v1.3](https://github.com/tableau/TabMon/releases/tag/v1.3).

I am going to close this now.
-Dan
