### ISSUE TITLE
Event logs

### ISSUE THREAD

**Issue by yapnel** [tableau/TabMon#186]
Hi

Is tabmon able to probe the Windows event logs? This is really useful for capturing errors Tableau is writing to Windows application event logs. 

Thanks

Nelson

**Comment by slewt** [comment]
That is not included in current functionality. It would take quite a bit of analysis to see if it will even be possible and any solution would need to accomodate both Windows and Linux, so doubt this will be implemented anywhere in the near future. 

Potential other solutions to pull that data if you have Splunk or an ELK stack or other syslog type solutions, there are several open source solutions to pull the event viewer logs from then and do your alerting in a different application there.

**Comment by danjrahm** [comment]
Hello @yapnel,

Currently TabMon is not able to parse the Windows Application logs. We can add this as a feature request but I'm not sure if this will fit within the scope of TabMon.

I'll mark this as a suggestion.

Thanks,
Dan

**Comment by danjrahm** [comment]
Didn't mean to close. Reopening.
