### ISSUE TITLE
Problem connecting to the data source "TabMon"

### ISSUE THREAD

**Issue by danjrahm** [tableau/TabMon#189]
I am also facing same issue please help me.

**Comment by ankunil** [comment]
Hi Danjrahm,

Here I am attaching blog files.

[TabMon.log.txt](https://github.com/tableau/TabMon/files/2463528/TabMon.log.txt)


[TabMon.config.txt](https://github.com/tableau/TabMon/files/2463529/TabMon.config.txt)

[TabMonResult_20181009_022511.csv.txt](https://github.com/tableau/TabMon/files/2463553/TabMonResult_20181009_022511.csv.txt)

I have followed same steps whatever mentioned in User guide. But I am facing below issue. 

ERROR: relation "public.countersamples" does not exist; Error while executing the query
The table "[public].[countersamples]" does not exist.
Unable to connect to the server "localhost". Check that the server is running and that you have access privileges to the requested database.

![error](https://user-images.githubusercontent.com/12734988/46719754-5ba7a000-cc8c-11e8-9063-aa3e1c584fa9.PNG)

I have tried <OutputMode value="csv"/> with "db" as well.

could you please help ASAP. I have very urgent need.

Thanks
Ankunil Das

**Comment by ankunil** [comment]
Hi Danjrahm,

Here I am attaching blog files.

[TabMon.log.txt](https://github.com/tableau/TabMon/files/2463528/TabMon.log.txt)


[TabMon.config.txt](https://github.com/tableau/TabMon/files/2463529/TabMon.config.txt)

[TabMonResult_20181009_022511.csv.txt](https://github.com/tableau/TabMon/files/2463553/TabMonResult_20181009_022511.csv.txt)

I have followed same steps whatever mentioned in User guide. But I am facing below issue. 

ERROR: relation "public.countersamples" does not exist; Error while executing the query
The table "[public].[countersamples]" does not exist.
Unable to connect to the server "localhost". Check that the server is running and that you have access privileges to the requested database.

![error](https://user-images.githubusercontent.com/12734988/46719754-5ba7a000-cc8c-11e8-9063-aa3e1c584fa9.PNG)

I have tried <OutputMode value="csv"/> with "db" as well.

could you please help ASAP. I have very urgent need.

**Comment by danjrahm** [comment]
Hello,

The reason you are unable to connect is because TabMon is configured to write to a CSV file instead of a database. To change this, please change the OutputMode to value "DB". This will ensure that TabMon writes to a database. Once done, please stop TabMon, delete all logs, then start TabMon.

**Comment by ankunil** [comment]
Still I am facing same problem.

**Comment by ankunil** [comment]
Can I share my screen through Gtalk?

**Comment by ankunil** [comment]
[TabMon.log.txt](https://github.com/tableau/TabMon/files/2465266/TabMon.log.txt)

this one new log

**Comment by ankunil** [comment]
I have never installed postgresql

**Comment by ankunil** [comment]
Let me re install it

**Comment by danjrahm** [comment]
Hello @ankunil,

Were you ever able to resolve this?

Thanks,
Dan

**Comment by danjrahm** [comment]
Hello @ankunil,

I am going to close this due to inactivity. If this issue persists, please let me know.

Thanks,
Dan
