### ISSUE TITLE
TabMon not collecting backgrounder, vizql, services metric after upgrading Version 1.3

### ISSUE THREAD

**Issue by naveentalari** [tableau/TabMon#202]
TabMon not collecting backgrounder, vizql server metrics after upgrading to vesion 1.3.

we recently upgraded our Tableau server to version 2018.2, due to in compatibility issues we also upgraded previous TabMon 1.2 to v 1.3, configured as per the KB document and configured service port enabled and added Tabconfiguration content in cluster part.

After starting TabMon i can see only Gateway, Postgres, Tabportsrv services metrics, other metircs like backgrounder, vizql are not avaiable.

Please help me to fix this issue, we need to check pefrom before and after the upgrade.

Attaching snapshots and log file, Please need help ASAP.

Thanks,
Naveen

![tabmon](https://user-images.githubusercontent.com/36216722/49693637-b4b58680-fb9e-11e8-8270-d7df9212c636.png)
![tabmon2](https://user-images.githubusercontent.com/36216722/49693652-f0505080-fb9e-11e8-92f2-abb27f872872.png)
[TabMon.log.txt](https://github.com/tableau/TabMon/files/2660249/TabMon.log.txt)

**Comment by ugamarkj** [comment]
Same thing here. I noticed that the process descriptions in task manager now says things like "run-backgrounder", so I wonder if it is due to a change in Tableau Server architecture. I'm running 2018.2. I tried changing the config file instance names to include "run-", but that didn't work.

**Comment by naveentalari** [comment]
Hi Team,

Can anyone please help us quickly. 

Thanks in advance. 

Thanks, 
Naveen

**Comment by naveentalari** [comment]
Hi Team,

Can anyone please help us quickly. 

Thanks in advance. 

Thanks, 
Naveen

**Comment by naveentalari** [comment]
Hi Dan,

Any update on this? Appreciate if you could look on this. Many Thanks!

Thanks,
Naveen

**Comment by naveentalari** [comment]
Hi Dan,

Great to hear this from you, Waiting for the update, Many Thanks!

- Naveen

**Comment by danjrahm** [comment]
Hello @naveentalari and @ugamarkj,

I believe this issue was due to a bug in the workbook. I uploaded the fixed workbook (in a zip file) to issue #204.

Please let me know if this issue persists after using the new workbook. If it does, we will continue troubleshooting the issue. Until then, I am going to close this.

Thanks,
Dan

**Comment by naveentalari** [comment]
Hello Dan,

Thanks for the workbook, That's fixed the issue.

Now i can see all services metrics on what's going on page.

Thanks for your efforts, Much appreciated.

Thanks,
Naveen
