### ISSUE TITLE
Tableau 10.5 Compatibility Question

### ISSUE THREAD

**Issue by nlian** [tableau/TabMon#207]
Hi,

We are using Tableau 10.5, is it better to install Tabmon 1.3 or Tabmon 1.2?

Thanks,

Lian

**Comment by danjrahm** [comment]
Hello @nlian,

Either will work but I would recommend TabMon 1.3. TabMon 1.3 has all of the latest changes and fixes.

Let me know if you have any other questions.

-Dan

**Comment by nlian** [comment]
Thanks DanOn 18 Dec. 2018 11:42 am, Dan Rahm <notifications@github.com> wrote:Hello @nlian,
Either will work but I would recommend TabMon 1.3. TabMon 1.3 has all of the latest changes and fixes.
Let me know if you have any other questions.
-Dan

**Comment by danjrahm** [comment]
Great. I am closing this now.
