### ISSUE TITLE
No data on the Dashboard

### ISSUE THREAD

**Issue by Mallikakm10** [tableau/TabMon#208]
After upgradation of Tableau Server 2018.1.6, Tabmon workbook showing no records. Kindly advise

**Comment by danjrahm** [comment]
Hello,

Before we begin this investigation I have a couple of questions.

1. What version of Tableau did you upgrade from?
2. What version of the TabMon.config are you using?
3. What version of TabMon are you using?
4. What version of the workbook are you using?

Once I have a response to these questions I should be able to figure out what is going on.

Thanks,
Dan

**Comment by mhelfand** [comment]
I am also not getting any data information. Running v1.3 and have Desktop 10.5.4

**Comment by danjrahm** [comment]
Hello,

**Comment by Mallikakm10** [comment]
This issue got resolved. If i change the Time zone offset as 8 and minute interval as 1 and Time as 2 years then im getting the data. Thank you

**Comment by danjrahm** [comment]
Hi @Mallikakm10,

That's great to hear. If you have any other questions, please let me know.

Thanks,
Dan

**Comment by danjrahm** [comment]
@mhelfand's issue is being handled in #209.

Closing this issue.
