### ISSUE TITLE
What type of cpu/memory impact should be expected with running tabmon? 

### ISSUE THREAD

**Issue by TroyHamilton** [tableau/TabMon#21]

**Comment by mchentableau** [comment]
Hi TroyHamilton, while it depends on your particular setup, in our tests we found that TabMon usually takes up less than 1% CPU on an 8 core system, in addition TabMon only uses resources when pulling, not when idle, overall we designed TabMon to be as lightweight as possible.

**Comment by jmangue** [comment]
Closing this out as answered, please reopen if you have any followup questions!
