### ISSUE TITLE
Could not initialize writer: FATAL: 28P01: password authentication failed for user "tabmon"

### ISSUE THREAD

**Issue by Tabuser** [tableau/TabMon#210]
Hi,
I am unable to start the tabmon sevices as I am getting "Access denied". When I check the logs, I see the error msg as **"Could not initialize writer: FATAL: 28P01: password authentication failed for user "tabmon"".** I tried reinstalling Tabmon multiple times with the postgres and without postgres(separate installation) but no luck. I am using the default password for TabMon db as mentioned in the tabmon.config file. Ironically, it does not allow me via pgadmin as well. I am attaching the logs and tabmon.config file as well. I have installed 1.3V to monitor the 2018.2.5 Tableau server.Any help is appreciated.

2019-01-10 10:39:43,966 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2019-01-10 10:39:44,013 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2019-01-10 10:39:44,013 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2019-01-10 10:39:44,201 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: FATAL: 28P01: password authentication failed for user "tabmon"
2019-01-10 10:39:44,217 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Hosts='Primary\xx.xx.xx.x \<Hostname1-FQDN>,Primary\xx.xx.xx.x \<Hostname2-FQDN>,Primary\xx.xx.xx.x \<Hostname3-FQDN>', Writer='null', PollInterval='5', TableName='countersamples']
2019-01-10 10:39:44,217 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2019-01-10 10:39:44,217 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2019-01-10 10:39:44,217 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2019-01-10 10:39:44,217 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)

Thanks

**Comment by Tabuser** [comment]
Below is the 
<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="5"/>
  
  <Clusters>
    <Cluster name="Primary">
    	  <Host computerName="Host1-FQDN" address="xx.xxx.xx.x" specifyPorts="true">
        <ProcessType processName="dataserver">
          <Process portNumber="8943" processNumber="0"/>
          <Process portNumber="8865" processNumber="1"/>
        </ProcessType>
        <ProcessType processName="vizql">
          <Process portNumber="8340" processNumber="0"/>
          <Process portNumber="8160" processNumber="1"/>
          <Process portNumber="8389" processNumber="2"/>
          <Process portNumber="8018" processNumber="3"/>
        </ProcessType>
        <ProcessType processName="vizportal">
          <Process portNumber="8284" processNumber="0"/>
          <Process portNumber="8682" processNumber="1"/>
        </ProcessType>
      </Host>
      <Host computerName="Host2-FQDN" address="xx.xxx.xx.x" specifyPorts="true">
        <ProcessType processName="dataserver">
          <Process portNumber="8879" processNumber="0"/>
          <Process portNumber="8473" processNumber="1"/>
        </ProcessType>
        <ProcessType processName="vizql">
          <Process portNumber="8952" processNumber="0"/>
          <Process portNumber="8673" processNumber="1"/>
          <Process portNumber="8759" processNumber="2"/>
          <Process portNumber="8202" processNumber="3"/>
        </ProcessType>
        <ProcessType processName="vizportal">
          <Process portNumber="8633" processNumber="0"/>
          <Process portNumber="8083" processNumber="1"/>
        </ProcessType>
      </Host>
      <Host computerName=""Host3-FQDN" address="xx.xxx.xx.x"" specifyPorts="true">
        <ProcessType processName="background job monitor">
          <Process portNumber="8368" processNumber="0"/>
          <Process portNumber="8019" processNumber="1"/>
          <Process portNumber="8081" processNumber="2"/>
          <Process portNumber="8697" processNumber="3"/>
          <Process portNumber="8874" processNumber="4"/>
          <Process portNumber="8929" processNumber="5"/>
          <Process portNumber="8476" processNumber="6"/>
          <Process portNumber="8654" processNumber="7"/>
          <Process portNumber="8331" processNumber="8"/>
          <Process portNumber="8787" processNumber="9"/>
          <Process portNumber="8572" processNumber="10"/>
          <Process portNumber="8567" processNumber="11"/>
          <Process portNumber="8714" processNumber="12"/>
          <Process portNumber="8130" processNumber="13"/>
          <Process portNumber="8565" processNumber="14"/>
          <Process portNumber="8852" processNumber="15"/>
          <Process portNumber="8748" processNumber="16"/>
          <Process portNumber="8664" processNumber="17"/>
          <Process portNumber="8848" processNumber="18"/>
          <Process portNumber="8001" processNumber="19"/>
        </ProcessType>
      </Host>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
    
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    
    <PurgeOldData enabled="true" thresholdDays="365"/>
  </Database>
</TabMonConfig>

**Comment by Tabuser** [comment]
The issue has been resolved.Had to uninstall another version of postgres as its was conflicting with the tabmon postgres. I later got another issue " failed to initialize counter sample using counters from configuration file: The given key was not present in the dictionary" which was resolved after adding all the processes in all the hosts.

**Comment by Tabuser** [comment]
Now I am able to view the report, but looks like there are few fields (invocation_count for example) that are not compatible with 2018.2.5 because of which the dashboards (vizql Bootstrap Activity,Concurrent users,cache hit/miss analysis) does not show any data.

**Comment by danjrahm** [comment]
Hello @Tabuser,

The issue with incomplete data showing in the workbook should be resolved by downloading and using the workbook in issue #204.

The cause of the issue is that the counters were renamed in Tableau Server 2018.2.

If there are any other issues let me know.
-Dan
