### ISSUE TITLE
Tamon instance #

### ISSUE THREAD

**Issue by JeffStrauss18** [tableau/TabMon#211]
In the prior Tabmon 1.3 releases, the instance # of the process would be split out into the Postgres database.  This appears to not be the case with 1.3.  Can you please confirm or offer any thoughts?

**Comment by danjrahm** [comment]
Hell Jeff,

This should still be the same. Are you using a newer version of Tableau or has your topology changed?

Thanks,
Dan

**Comment by JeffStrauss18** [comment]
We are using 2018.3.2 and Tabmon 1.3 both on Windows.  See attached, we're only capturing the JMX counters with Tabmon.  I can also share with you our config, if you need this.

![tabmon_screenprint_db](https://user-images.githubusercontent.com/16765302/51703707-adc2c600-1fdc-11e9-943e-062913b1a887.png)

**Comment by danjrahm** [comment]
Hey @JeffStrauss18,

Would you mind passing me the config and your TSM topology output?

The topology can be gathered by running the following commands.
1. tsm login -u [USERNAME]
2. tsm topology list-ports > [OUTPUT_FILE]

I may also need logs at some point, but this information should be a good start.

Thanks,
Dan

**Comment by danjrahm** [comment]
Hey @JeffStrauss18,

There have been no major architecture changes between 2018.3.0 and 2018.3.2. TSM topology will tell me the ports the JMX counters are exposed on. This will allow me to confirm whether or not the ports are properly set in the config.

Thanks,
Dan

**Comment by JeffStrauss18** [comment]
Here's a listing of the ports.

[ts_prod_port.txt](https://github.com/tableau/TabMon/files/2809362/ts_prod_port.txt)

**Comment by danjrahm** [comment]
Hi @JeffStrauss18,

Can you also send me the TabMon config?
The config is located here: <INSTALL_ROOT>\TabMon\Config\TabMon.config

Feel free to scrub any IP addresses or computer names from the config. This combined with the port info will help us figure out if everything is configured properly. 

Thanks,
Dan

**Comment by JeffStrauss18** [comment]
Here you go.
[TabMon.zip](https://github.com/tableau/TabMon/files/2814542/TabMon.zip)

**Comment by danjrahm** [comment]
Hey @JeffStrauss18,

I think the issue is due to a configuration issue. Some of the ports didn't match the topology output.

Here is the adjusted host section. Try dropping this into TabMon config:
```
<Host computerName="ORD-TBL104" address="ORD-TBL104" specifyPorts="true">
  <ProcessType processName="vizql">
    <Process portNumber="8658" processNumber="0"/>
    <Process portNumber="8580" processNumber="1"/>
    <Process portNumber="8840" processNumber="2"/>
    <Process portNumber="8208" processNumber="3"/>
  </ProcessType>
  <ProcessType processName="vizportal">
    <Process portNumber="8149" processNumber="0"/>
    <Process portNumber="8774" processNumber="1"/>
  </ProcessType>
</Host>
<Host computerName="ORD-TBL105" address="ORD-TBL105" specifyPorts="true">
  <ProcessType processName="vizql">
    <Process portNumber="8582" processNumber="0"/>
    <Process portNumber="8757" processNumber="1"/>
    <Process portNumber="8008" processNumber="2"/>
    <Process portNumber="8858" processNumber="3"/>
  </ProcessType>
  <ProcessType processName="vizportal">
    <Process portNumber="8889" processNumber="0"/>
    <Process portNumber="8144" processNumber="1"/>
  </ProcessType>
</Host>
```

Let me know if this resolves the issue.

Thanks,
Dan

**Comment by danjrahm** [comment]
Hello,

I am going to close this issue due to inactivity. If the issue is still occurring please let me know.

Thanks,
Dan
