### ISSUE TITLE
tabmon service failed to start with multiple hosts in 2018.2 version

### ISSUE THREAD

**Issue by parameshjoy** [tableau/TabMon#228]
Hello Team,

When i try to update tabmon.config file with multiple host am unable to start the services. this is under 2018.2

 <Clusters>
    <Cluster name="Primary">
      <Host computerName="wcw31230" address="wcw31230" specifyPorts="true">
	  <Host computerName="wcw31228" address="wcw31228" specifyPorts="true">
	  <Host computerName="wcw31229" address="wcw31229" specifyPorts="true">
	   <ProcessType processName="dataserver">
		<Process portNumber="8203" processNumber="0"/>
		<Process portNumber="8222" processNumber="0"/>
		<Process portNumber="8515" processNumber="1"/>
		<Process portNumber="8123" processNumber="1"/>
	   </ProcessType>
	   <ProcessType processName="vizql">
		<Process portNumber="8083" processNumber="0"/>
		<Process portNumber="8673" processNumber="0"/>
		<Process portNumber="8436" processNumber="1"/>
	    <Process portNumber="8551" processNumber="2"/>
	   </ProcessType>
	   <ProcessType processName="vizportal">
		<Process portNumber="8261" processNumber="0"/>
	   </ProcessType>
	   </Host>
	   </Host>
	   </Host>
	 </Cluster>
  </Clusters>

**Comment by parameshjoy** [comment]
<Clusters>
    <Cluster name="Primary">
      <Host computerName="wcw31230" address="wcw31230" specifyPorts="true">
	  <Host computerName="wcw31228" address="wcw31228" specifyPorts="true">
	  <Host computerName="wcw31229" address="wcw31229" specifyPorts="true">
	   <ProcessType processName="dataserver">
		<Process portNumber="8203" processNumber="0"/>
		<Process portNumber="8222" processNumber="0"/>
		<Process portNumber="8515" processNumber="1"/>
		<Process portNumber="8123" processNumber="1"/>
	   </ProcessType>
	   <ProcessType processName="vizql">
		<Process portNumber="8083" processNumber="0"/>
		<Process portNumber="8673" processNumber="0"/>
		<Process portNumber="8436" processNumber="1"/>
	    <Process portNumber="8551" processNumber="2"/>
	   </ProcessType>
	   <ProcessType processName="vizportal">
		<Process portNumber="8261" processNumber="0"/>
	   </ProcessType>
	   </Host>
	   </Host>
	   </Host>
	 </Cluster>
  </Clusters>

**Comment by danjrahm** [comment]
Hello @parameshjoy,

In order to best troubleshoot this issue I will need the following information:
1. The version of TabMon being used.
2. The TabMon configuration that is being used. (Private information can be redacted)
3. A set of TabMon logs from the last time you attempted to start TabMon.

Once I receive the information above, I should be able to take a look at the issue.

Thanks,
Dan

**Comment by abhijeettote1989** [comment]
@danjrahm,

I am facing the same issue. I have 2 different environments where single node cluster is working fine and 3 node cluster is not working. Its throwing error that it unable to communicate with jmx port however i am able to telnet the ports fine. 
![error log snap](https://user-images.githubusercontent.com/42025422/60512460-75a96880-9c89-11e9-8ccf-03e1a6f9e39e.PNG)

**Comment by danjrahm** [comment]
Hello @abhijeettote1989,

Excuse the delay in my response. I have moved your current issue over to issue #233. I will start my investigation there.

Thank you,
Dan
