### ISSUE TITLE
Invalid TabMon options

### ISSUE THREAD

**Issue by tslinkardKH** [tableau/TabMon#230]
I can't start the tabmon service on a 2019.2 server.  I get the error "[5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting.."

I'm guessing it's in the Process Types but I don't see any issues.  
[TabMon.zip](https://github.com/tableau/TabMon/files/3299150/TabMon.zip)

**Comment by tslinkardKH** [comment]
any thoughts on this?  maybe a working config file for 2019.2 that I can just modify?

**Comment by tslinkardKH** [comment]
[TabMon.log.zip](https://github.com/tableau/TabMon/files/3303363/TabMon.log.zip)
here is the log and config file

**Comment by tslinkardKH** [comment]
sorry about this.  turns out the tabmon just didn't have correct permissions in the DB.

**Comment by danjrahm** [comment]
Hi @tslinkardKH,

Sorry about the delay on this. I'm glad you got everything figured out!

If you have any other questions let me know.

Thanks,
Dan
