### ISSUE TITLE
unable to stop Tabmon

### ISSUE THREAD

**Issue by nikhilakommireddy** [tableau/TabMon#231]

**Comment by nikhilakommireddy** [comment]
I installed and configured TabMon along with Postgres. Intially I set the <OutputMode value="csv"/> but want to change it to "DB". As per teh suggestion in one of your ports, i tried stopping teh Tabmon First but that doesnt seem to happen. Nothing is logged in the logs as well. 
Even after executing "Stop Tabmon" witha mdin rights Tabmon is still running in servcies.msc. 
Please suggest how to proceed.
[TabMon.log.txt](https://github.com/tableau/TabMon/files/3310972/TabMon.log.txt)

**Comment by danjrahm** [comment]
Hello @nikhilakommireddy,

This sounds a bit like a permissions issue. I think the best way to stop it would be using the command prompt. To do this, do the following:

1. Start the command prompt as an administrator.
2. Run the kill command below:
sc stop tabmon

Once this is done, the service should be stopped.

Let me know how this works.
-Dan

**Comment by nikhilakommireddy** [comment]
Thanks Dan. I will give it a try😊

**Comment by nikhilakommireddy** [comment]
Thanks Dan. This worked. I am also now able to connect to Tabmon DB to view the default workbook.

**Comment by danjrahm** [comment]
Hey @nikhilakommireddy,

I'm glad you got everything working. Let me know if you have any other questions.

Thanks,
Dan
