### ISSUE TITLE
WhDre is the installer?

### ISSUE THREAD

**Issue by spookymonster** [tableau/TabMon#25]
In the user guide, under Installing tabmon, it simply says "Run the installer". What is the executable name? Which folder can I find it in? I can't find a file named tabmon.exe or installtabmon.exe anywhere. Am I supposed to build it first?

**Comment by jmangue** [comment]
Hi there!

A pre-built installer can be downloaded from the Releases page: https://github.com/tableau/TabMon/releases

If you are building from source, the output directory for the installer is <Source Root>\TabMonServiceInstallerBootstrapper\bin\Release\

**Comment by spookymonster** [comment]
Found it.  Thanks.
