### ISSUE TITLE
tabmon wont install

### ISSUE THREAD

**Issue by Batwoman007** [tableau/TabMon#250]
Hi all.  I have run through the pre-requisites for installing Tableau. Am logged in as a local windows administrator.  I have right clicked on InstallRabMon and run as administrator.  I click on install (with the option to install and initialise Postgres selected) and it appears to try and install Postgres then comes up with an error saying one or more issues caused the setup to fail.  0x80070001 - incorrect function is the message. I have looked at the log but cannot determine what the issues is. 

Can anyone help please?

[tabmon install error log.txt](https://github.com/tableau/TabMon/files/4987140/tabmon.install.error.log.txt)

**Comment by danjrahm** [comment]
Hello,

I would suggest installing without Postgres. Once that is done you can manually install and configure postgres using the "Manually Installing and Configuring Postgres" section of the appendix [here](https://tableau.github.io/TabMon/docs/tabmon_appendix_a).

If you are still running into issues after this, please let me know.

Thanks, 
Dan

**Comment by Batwoman007** [comment]
Thanks will try that
