### ISSUE TITLE
Workbook is blank

### ISSUE THREAD

**Issue by spookymonster** [tableau/TabMon#26]
I've started up the Tabmon and Postgres services. I've checked the log, and the only errors I see there are regarding the network interface counter not being a single instance (which appears to be a known problem).  I started up the workbook and successfully entered the Server Auditing and Tabmon passwords. I have confirmed that the data sources are passing data, however the dashboards are all completely blank (except for the Glossary). I see all the dashboard tabs, and the sheet headers ("%CPU by Tableau Server Service - Select to See Details), and I can even go to the sheets and confirm they're defined, but they're not showing any data. The only page that has anything on it is the Glossary. It appears to be showing live data, because the numbers change when I refresh the data. Any suggestions?

**Comment by spookymonster** [comment]
Interesting.... when I change the Time Zone Offset on the "What's Going On?" Dashboard from -7 to 0, things start appearing again.

**Comment by jmangue** [comment]
That's odd; I haven't seen this issue before.  Is this still happening for you or did the one-time Time Zone tweak force everything to start refreshing properly?

**Comment by spookymonster** [comment]
Looks like we can change it back to -7 after we have at least 7 hours worth of data.
