### ISSUE TITLE
Invalid results for Memory in Use?

### ISSUE THREAD

**Issue by spookymonster** [tableau/TabMon#27]
The Memory in Use view is showing over 140% for the last 10 hours, before finally dropping below 80% this morning. Our actual memory usage never went _above_ 80% in the last 24 hours. From what I understand of % Committed Bytes in Use, hitting 100% indicates you're using all real memory, as well as all page memory, so results above 100% should be impossible. Am I misinterpreting these numbers, or is this a bug?

**Comment by jmangue** [comment]
Hi spookymonster!  Sorry about the confusion; this is a known issue.  The data being collected by TabMon is correct, but the Memory dashboard in the sample workbook is not correctly aggregating the data, which will be corrected in the next release.

In the meantime you can download a workbook where this has been corrected from the development branch: https://github.com/tableau/TabMon/blob/dev/Sample%20Workbooks/TabMon%20Workbook.twb
.. or alternately you can get in and play with the data yourself to make your own view.  The data is there, go wild!

**Comment by spookymonster** [comment]
Much better. Thanks.

**Comment by ManoSahoo165** [comment]
ello Team,
we installed Tabmon on our environment (version 9.0). but while validating data we are getting blank for Network sheet and we have null values for measures present on dashboard.

Kindly Help me to fix the issue.

Thanks
Manoj

**Comment by danjrahm** [comment]
@ManoSahoo165 
Moved this request for assistance to issue #49 . I will respond there.
