### ISSUE TITLE
Unable to Open TabMon Sample Workbook

### ISSUE THREAD

**Issue by agreenhaw** [tableau/TabMon#35]
Hello!

I am unable to open the sample TabMon .twb file provided here: 

https://github.com/tableau/TabMon/tree/master/Sample%20Workbooks

When I open it I get the following error message:
![github](https://cloud.githubusercontent.com/assets/16658699/12252934/e49c396c-b898-11e5-900f-caee51c1e2de.jpg)

Can someone please help me troubleshoot this error? Thank you in advance!

Best,
Angie Greenhaw

**Comment by agreenhaw** [comment]
I had been downloading the TWB using the "save link as" option. Copying and pasting the TWB contents into a text editor and saving the file with the TWB extension fixed it right up.

**Comment by danjrahm** [comment]
Hello Angie,

Sorry about the late response. I'm glad that you were able to download the workbook!

Let me know if there are any other questions.

Thanks,
Dan
