### ISSUE TITLE
Does TabMon support Tableau server 9.2?

### ISSUE THREAD

**Issue by nguyenbui** [tableau/TabMon#37]
Hi,

I deployed TabMon and everything works fine so far. However when i open the TabMonWorkbook, i can't see any data or charts. It seems to be blank.
Not sure if TabMon supports Tableau 9.2 here, as I used the latest version already.

Thanks!
Nguyen

**Comment by jmangue** [comment]
TabMon does support 9.2.  Is there any data at all being written to the countersamples table or is it totally empty?  

One thing to check would be to open Services.msc and make sure TabMon is running.  We've seen issues where users use the Start Menu shortcut to start the service, but don't have admin privileges when they do so, so it silently fails to start.  Issue #34 

If TabMon is running and nothing is being written, you'll probably need to crack into the TabMon logs to see what the error is...  let me know what you find out and I'll try to help.

**Comment by jmangue** [comment]
Closing out as inactive, please reopen if you still need some help.
