### ISSUE TITLE
Trouble with tabmon install/accessing thru tabmon workbook

### ISSUE THREAD

**Issue by SrujanYada** [tableau/TabMon#38]
We installed tabmon few minutes back and when trying to access the tabmon workbook, got the error as shown below. can you please suggest why the error and what the fix to the error is?
![capture](https://cloud.githubusercontent.com/assets/16767471/12405245/cc9d9d1e-be07-11e5-8c00-34c0d9e5c41c.PNG)
I also tried to check for dbcreation log.. couldnt find one. there is a tabmon log.
also, when i tried to start & stop tabmon.. a CSV file was generated but most of the counters were null. please suggest.

**Comment by danjrahm** [comment]
Hello Srujan,

The first thing I would check is whether Tabmon-Postgres is installed and running. This can be done by opening up Services.msc and scrolling down to TabMon-Postgres. If installed and running you should see the service with "started" in the "status" column.

Let me know what you see. The result of this will tell me our next steps. 

-Dan

**Comment by SrujanYada** [comment]
Hi Dan
I see it installed/running. Please find the screenshot below:

[cid:image001.png@01D15221.84D82050]

Thanks,
Srujan

**Comment by SrujanYada** [comment]
Hi Dan
I earlier tried to install tabmon with "Install and initialize postgres for me" option checked on our tableau server. When i check for the tables in tabmon database after the install is completed, i see no relations displayed.  

Please refer to https://github.com/tableau/TabMon/issues/6 for more info.

can you please suggest on how to proceed? I see there is an issue with postgres install.

**Comment by jmangue** [comment]
Sounds like you're up and running from the other thread, closing this out.

**Comment by SrujanYada** [comment]
Hi Justin
We have started using tabmon workbook and are having trouble understanding the graphs. Is there a user guide to the tabmon workbook that explains the graphs? How can I see why my memory usage is very high and who/what is causing it?

Regards,
Srujan

**Comment by SrujanYada** [comment]
Hi Justin
Tabmon workbook seem to have issues on every view of it. Can you suggest when was the latest release for this workbook? Can you please share the updated version so we can use it?

Regards,
Srujan

From: Yada, Srujan (Oil & Gas, Non-GE)
Sent: Thursday, January 21, 2016 10:37 AM
To: 'tableau/TabMon'; tableau/TabMon
Subject: RE: [TabMon] Trouble with tabmon install/accessing thru tabmon workbook (#38)

Hi Justin
We have started using tabmon workbook and are having trouble understanding the graphs. Is there a user guide to the tabmon workbook that explains the graphs? How can I see why my memory usage is very high and who/what is causing it?

Regards,
Srujan

**Comment by danjrahm** [comment]
Hey Srujan,

We have noticed a few inconsistencies in our example workbook. We are planning on updating the workbook in our next release. We will also work on creating a story that describes what is happening in each sheet.

The purpose of the sample workbook was to show what can be done with the data. We find that the true value is in the data source itself. 

If there are any questions let me know. Once we make our next release the workbook should be updated.

-Dan

**Comment by SrujanYada** [comment]
Hi Dan
Can you let us know when is the next planned release?

-Srujan

**Comment by danjrahm** [comment]
Hello Srujan,

Currently we do not have an exact date for our next release. But, we have been discussing a release in the next couple of months. 

Thanks,
Dan

**Comment by vinothdakshin** [comment]
Hello Dan,

I have installed TabMon recently, I couldnt see any graph in the tableau workbook.
![image](https://user-images.githubusercontent.com/30115690/32722211-27f66658-c88f-11e7-8e4b-bd46a0d95b24.png)
can you please help me urgently, am i missing something..why no data has populated.?
