### ISSUE TITLE
FATAL TabMon.TabMonAgent - Invalid TabMon options specified! Aborting..

### ISSUE THREAD

**Issue by santoshadari** [tableau/TabMon#40]
Hi,

I am unable to start tabmon services, below is the error i am seeing in logs.

Anyhelp is appreciated

INFO TabMon.TabMonAgent - Initializing TabMon..
2016-02-04 17:29:14,685 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2016-02-04 17:29:14,685 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)

**Comment by danjrahm** [comment]
Hello,

It looks like there is an issue in either the tabmon.config or counter.config file. Can you email me those files? I should be able to spot the issue that way. 

Feel free to scrub any passwords or sensitive data out of the configs.

Thanks,
Dan

**Comment by santoshadari** [comment]
Hi Dan,

Uninstalling and installing tabmon with postgres config resolved this problem and able to install Tabmon in my workers as well.

But I can only see primary data when I open workbook, I am using the below code in all the 3 tabmon config files.

Please let me know if I am missing anything here.



<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="30"/>
  
  <Clusters>
    <Cluster name="vmwprimary-tst">
                  <Host name="vmwprimary-tst.hq.netapp.com"/>
      <Host name="VMWWORKER1.hq.netapp.com"/>
                  <Host name=" VMWWORKER2.hq.netapp.com"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
  </Database>
</TabMonConfig>

Thanks,
Santosh Adari
BI Analyst / Tableau BI Architect
408-419-5606
[Description: Description: http://media.netapp.com/images/go-further-faster-esignature-373x78.jpg]<http://www.netapp.com/us/?REF_SOURCE=emmbonrunnersignaturehp-us>

**Comment by jmangue** [comment]
Hi Santosh,

A couple things to get you up and running:

1) In the config you sent, the Host element for VMWWORKER2 has a leading space in it, you should remove this.
2) In order for TabMon to poll the workers, you will need to configure the TabMon Service to log on with a service account which also has admin access on both of the remote machines.  There are instructions on how to do this in the "Remote Polling" section on page 4 of the [TabMon User Guide](https://github.com/tableau/TabMon/blob/master/TabMonService/Documentation/UserGuide.pdf).  Also you will want to make sure the Windows "Remote Registry" service is running on all of the computers, but this is usually not an issue.

If you do both of those things and still see an issue, please follow up and we'll go into more depth.

**Comment by santoshadari** [comment]
Thanks Justin,

I was able to figure out the issue with cluster name and it was able to pool data from clusters, but now my only issue is fixing the below errors.

When i enable jmx service I am getting a port conflict error.

[cid:image001.png@01D16015.1B50E0C0]

Thanks,
Santosh Adari
BI Analyst / Tableau BI Architect
408-419-5606
[Description: Description: http://media.netapp.com/images/go-further-faster-esignature-373x78.jpg]<http://www.netapp.com/us/?REF_SOURCE=emmbonrunnersignaturehp-us>

**Comment by jmangue** [comment]
Hi Santosh,

Unfortunately I'm unable to see the error screenshot.  What is the text/body of the JMX port error you're seeing, and where are you seeing it?  In TabMon or in Tableau Server?

**Comment by santoshadari** [comment]
Hi Justin,

Here is what I see in Tableau logs, when I enable JMX  and start Tableau server.

Blocked or conflicting ports found on worker worker2-stg. See worker tabadmin.log for details.
2016-02-05 14:08:04.952 -0800_DEBUG_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Running report_blocked_ports on worker2: worker1-prd:3730
2016-02-05 14:08:05.311 -0800_WARN_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Blocked or conflicting ports found on worker worker1-prd. See worker tabadmin.log for details.
2016-02-05 14:08:05.358 -0800_DEBUG_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Running begin_stop on worker1: worker2-stg:3730
2016-02-05 14:08:05.436 -0800_DEBUG_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Running begin_stop on worker2: worker1-prd:3730
2016-02-05 14:08:05.514 -0800_DEBUG_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Running begin_stop on worker1: worker2-stg:3730
2016-02-05 14:08:05.592 -0800_DEBUG_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Running begin_stop on worker2: worker1-prd:3730
2016-02-05 14:08:05.795 -0800_DEBUG_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Running wait_stop on worker1: worker2-stg:3730
2016-02-05 14:08:05.888 -0800_DEBUG_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Running wait_stop on worker2: worker1-prd:3730
2016-02-05 14:08:06.600 -0800_DEBUG_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Tableau Server cannot start due to blocked ports.
2016-02-05 14:08:06.600 -0800_INFO_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Unable to determine if all components of the service started properly. See "tabadmin.log" for more information.
2016-02-05 14:08:06.600 -0800_DEBUG_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Running status on worker1: worker2-stg:3730
2016-02-05 14:08:06.185 -0800_DEBUG_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ Running status on worker2: worker1-prd:3730
2016-02-05 14:08:06.356 -0800_EXACT_10.102.70.133:VMWPRIMARY-TST_:_pid=11324_0x3f685162__user=__request=__ VMWPRIMARY-TST:
                Status: STOPPED
worker2-stg:
                Status: STOPPED
worker1-prd:
                Status: STOPPED


Thanks,
Santosh Adari
BI Analyst / Tableau BI Architect
408-419-5606
[Description: Description: http://media.netapp.com/images/go-further-faster-esignature-373x78.jpg]<http://www.netapp.com/us/?REF_SOURCE=emmbonrunnersignaturehp-us>

**Comment by jmangue** [comment]
Sounds like your Tableau Server nodes "worker2-stg" and "worker1-prd" either have other stuff running on the JMX ports, or else the ports JMX is trying to use are being blocked by firewall settings.

You can see the port ranges that JMX is trying to open up at http://onlinehelp.tableau.com/current/server/en-us/ports_jmx.htm

**Comment by santoshadari** [comment]
I tried, but now server is not coming up, will you be able to join for a quick call.

Thanks,
Santosh Adari
BI Analyst / Tableau BI Architect
408-419-5606
[Description: Description: http://media.netapp.com/images/go-further-faster-esignature-373x78.jpg]<http://www.netapp.com/us/?REF_SOURCE=emmbonrunnersignaturehp-us>

**Comment by jmangue** [comment]
Doh!  Try disabling JMX ports again with **tabadmin set service.jmx_enabled false** ->** tabadmin configure**

**Comment by santoshadari** [comment]
I did that but services not coming back, I have restarted my VM’s now but still no luck.

[cid:image001.png@01D16025.1E1341D0]

Thanks,
Santosh Adari
BI Analyst / Tableau BI Architect
408-419-5606
[Description: Description: http://media.netapp.com/images/go-further-faster-esignature-373x78.jpg]<http://www.netapp.com/us/?REF_SOURCE=emmbonrunnersignaturehp-us>

**Comment by jmangue** [comment]
Hi Santosh,

At this point, TabMon isn't involved as enabling the JMX ports is solely a feature of Server.  If your server is down, your best bet is to contact Tableau Technical Support and let them know you tried to enable JMX ports and now Server isn't coming back up.  They will be able to work with you 1:1 to get you back up and running ASAP.

**Comment by santoshadari** [comment]
Hi Justin,

Can you please confirm if config file need to be in same order in my 2 other workers ?

<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="30"/>
  
  <Clusters>
    <Cluster name="vmwprimary-tst">
                  <Host name="vmwprimary-tst.hq.netapp.com"/>
      <Host name="VMWWORKER1.hq.netapp.com"/>
                  <Host name="VMWWORKER2.hq.netapp.com"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
  </Database>
</TabMonConfig>


Thanks,
Santosh Adari
BI Analyst / Tableau BI Architect
408-419-5606
[Description: Description: http://media.netapp.com/images/go-further-faster-esignature-373x78.jpg]<http://www.netapp.com/us/?REF_SOURCE=emmbonrunnersignaturehp-us>

**Comment by santoshadari** [comment]
Hi Dan,

Here is the screenshot, I can access CPU data only from primary not from my other two workers. I am using the same configuration in all the VM’s.

<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="30"/>
  
  <Clusters>
    <Cluster name="vmwprimary-tst">
                  <Host name="vmwprimary-tst.hq.netapp.com"/>
      <Host name="VMWWORKER1.hq.netapp.com"/>
                  <Host name=" VMWWORKER2.hq.netapp.com"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
  </Database>
</TabMonConfig>


[cid:image002.png@01D16253.509F7490]

Thanks,
Santosh Adari
BI Analyst / Tableau BI Architect
408-419-5606
[Description: Description: http://media.netapp.com/images/go-further-faster-esignature-373x78.jpg]<http://www.netapp.com/us/?REF_SOURCE=emmbonrunnersignaturehp-us>

From: Adari, Santosh
Sent: Friday, February 05, 2016 11:36 AM
To: 'tableau/TabMon'; tableau/TabMon
Subject: RE: [TabMon] FATAL TabMon.TabMonAgent - Invalid TabMon options specified! Aborting.. (#40)

Hi Dan,

Uninstalling and installing tabmon with postgres config resolved this problem and able to install Tabmon in my workers as well.

But I can only see primary data when I open workbook, I am using the below code in all the 3 tabmon config files.

Please let me know if I am missing anything here.



<?xml version="1.0"?>

<TabMonConfig xmlns="TabMon">
  
  <OutputMode value="db"/>
  
  <PollInterval value="30"/>
  
  <Clusters>
    <Cluster name="vmwprimary-tst">
                  <Host name="vmwprimary-tst.hq.netapp.com"/>
      <Host name="VMWWORKER1.hq.netapp.com"/>
                  <Host name=" VMWWORKER2.hq.netapp.com"/>
    </Cluster>
  </Clusters>
  
  <Database name="TabMon" type="Postgres">
    <Server host="localhost" port="5432"/>
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
  </Database>
</TabMonConfig>

Thanks,
Santosh Adari
BI Analyst / Tableau BI Architect
408-419-5606
[Description: Description: http://media.netapp.com/images/go-further-faster-esignature-373x78.jpg]<http://www.netapp.com/us/?REF_SOURCE=emmbonrunnersignaturehp-us>

**Comment by jmangue** [comment]
Hi Santosh,

TabMon should only be running on one VM.  There should not be 3 TabMon config files -- just one.  It will collect data from all 3 computers if set up correctly.  You should remove TabMon from the other two computers and just leave it on the primary.

The VM running TabMon will need to be running the TabMon service using a user account that has permissions to remotely poll counters from the worker machines.  There is info on how to set this up on page 4 of the user guide. (https://github.com/tableau/TabMon/blob/master/TabMonService/Documentation/UserGuide.pdf)

**Comment by santoshadari** [comment]
Thanks Justin,

Its works perfectly now, appreciate your help on this.

Thanks,
Santosh Adari
BI Analyst / Tableau BI Architect
408-419-5606
[Description: Description: http://media.netapp.com/images/go-further-faster-esignature-373x78.jpg]<http://www.netapp.com/us/?REF_SOURCE=emmbonrunnersignaturehp-us>

**Comment by jmangue** [comment]
Hi Santosh, 

Glad to hear you're up and running!!  Let us know if you need more help.  Closing this issue out :)

**Comment by Shobananpa** [comment]
Leave a comment

**Comment by Shobananpa** [comment]
Hi Santhosh/Justin,

I need your help in installing tabmon.
We are also facing issues like the dataserver process going to stopped state when we enable JMX.
We changed the default port of dataserver process to 9750 & 9751, still its not working when we enable JMX.
We are stuck here, not able to proceed further to install tabmon.
@santoshadari Santhosh: what did you do when you faced similar issue. Could you please provide us a solution

Thanks,
Shoba

**Comment by santoshadari** [comment]
Hi Shoba,

I suspect some other applications might be using the same port which is causing this conflict, In our case we have uninstalled OBIEE application and changed the default port for dataserver.

Contact Tableau support if you are unable update port for dataserver.
Thanks,
Santosh Adari
BI Analyst / Tableau BI Architect
408-419-5606
[Description: Description: http://media.netapp.com/images/go-further-faster-esignature-373x78.jpg]<http://www.netapp.com/us/?REF_SOURCE=emmbonrunnersignaturehp-us>
