### ISSUE TITLE
Collecting Data for *All* Servers in a Cluster

### ISSUE THREAD

**Issue by agreenhaw** [tableau/TabMon#41]
Hello,

Today I installed TabMon for our 3-node cluster, but I'm only able to see metrics for the primary node. How can I configure TabMon so that it collects data for the other 2 nodes as well?

Thanks,
Angie Greenhaw

**Comment by jmangue** [comment]
Hi Angie,

If you open up the [user guide](https://github.com/tableau/TabMon/blob/master/TabMonService/Documentation/UserGuide.pdf) and go to page 4, there is a section called "Remote Polling Setup" that covers how to configure TabMon to poll results from multiple remote computers.  Basically it boils down to updating the TabMon config to include the worker hosts, and then making sure the service account TabMon is using has appropriate permissions on the workers.

Let me know if you need any additional help!

**Comment by SmartError** [comment]
Hi,
I have a cluster of one primary and one worker node and want to collect all data using TabMon.
I CAN collect all Tableau data ( JVM Health and Tableau Server Health ) from both servers, but 
I CANNOT get any Perfmon data (CPU, HDD, Memory etc.) from Worker node. I tried to have TabMon installed only on Primary server and also on both servers. strange thing is, that even from TabMon installed on Worker node I cannot get perfmon data - checked also directly in Postgres DB  in countersamples table. On both servers TabMon is running on same AD service account. 
In both TabMon DB on both servers following query has same result = no Perfmon data on Worker:
**select distinct machine, counter_type from countersamples**

**"machine"	"counter_type"**
"primary"	"Tableau Server Health"
"primary"	"JVM Health"
"primary"	"Perfmon"
"worker"	"JVM Health"
"worker"	"Tableau Server Health"

**Comment by jmangue** [comment]
Hi SmartError, that's interesting... A couple things to check:

On the worker that isn't getting perfmon data:
- Is the AD service account TabMon is using a member of the "Performance Monitor Users" and "Performance Log Users" groups?
- Are the "Remote Registry" and "Performance Logs & Alerts" services running?  These need to be running for applications to be able to remotely pull PerfMon data

There are TabMon logs in C:\Program Files (x86)\TabMon\Logs that may contain some helpful error information.

A side note, best practice is to just have one TabMon instance running that polls both servers.

Let me know how it goes.

**Comment by tableaugeek** [comment]
Hi Jmangue,

I am getting "Access Denied"  pop-up when i am trying to add my 2 workers to the TabMon config file, any idea why?

**Comment by jmangue** [comment]
Hi mytableau,

Hmmm, so you're getting access denied when trying to save an edit to the TabMon.config file in notepad?  Do you have write permissions on the folder where you installed TabMon?

**Comment by mytableau** [comment]
Yes when i edit and try to save it, i get the Access Denied message, also i do have Admin privileges on the folder, not sure what is wrong.

**Comment by SmartError** [comment]
Hi Justin,

Thanks a lot! I added that service account to those two groups and started
services you mentioned (these were running only on primary node) and now it
works like a charm. :-)

Now we need to solve some cleaning logic because there are quite a lot of
data (around  6M rows and 1,5GB per week). One option would be just delete
data over then n days, but we would like to have some long history data
too. Prolong capture interval would be one option, but then we may lose
some Tableau information. Another option could be to have some trigger in
DB to aggregate data older then n days (e.g. AVG/Sum per hour, but again,
we may lose big part of information). Any suggestion how to solve it?

Thanks,
Mirek
Dne 12. 2. 2016 2:54 napsal uživatel "Justin Mangue" <
notifications@github.com>:

**Comment by jmangue** [comment]
Hi Mirek!  Glad to hear you got it working.

Yeah, I feel your pain on the data volume.  The short term solution is to chop data older than a certain threshold, as you mentioned.

A better solution is to use some kind of DB trigger as you mentioned, or use Postgres' materialized views to routinely extract and aggregate data into historical tables.  This is a feature I'd like to bake into TabMon at some point but realistically is a ways off.

**Comment by jmangue** [comment]
Going to close out this issue, please feel free to open a new one if you need more help!

**Comment by Rakush** [comment]
I have configured the tabmon config file on my primary server and also added the host and cluster name of worker nodes in config file . it shows the all node in tabmon workbook   but not able to fetch the data from worker nodes , it shows only the data of primary. 
how to enable the data fetching and mapping from worker nodes in cluster?
please provide necessary changes we have to make in config file.

**Comment by vinothdakshin** [comment]
Hi,

I have installed TabMon V1.1 in Tableau Server, and manually installed the PostgreSQL 10. when i try to publish the tableau workbook which is available in resources folder, the Counter Samples table showing Red in Color as it is not found. How to I relate Tabmon with Postgre 10? also please confirm whether TabMon 1.1 will support Tableau Server V10.x? Kindly advise.

**Comment by vinothdakshin** [comment]
Hello,
I have installed TabMon recently, I couldnt see any graph in the tableau workbook.
![image](https://user-images.githubusercontent.com/30115690/32764943-2a0d4f66-c92e-11e7-8fa2-49f804c11754.png)
can you please help me urgently, am i missing something..why no data has populated.?
