### ISSUE TITLE
View taking too long to render

### ISSUE THREAD

**Issue by spookymonster** [tableau/TabMon#42]
Whenever I go into Tabmon, it takes 8+ minutes to render the view for the last 24 hours. Is this normal?

**Comment by jmangue** [comment]
Hi spookymonster,

It depends on how many counters you are collecting, your sample rate, and the specs on your database machine.  TabMon does generate a lot of data and this is currently up to the user to manage.  I'd recommend creating indexes on the table for whatever fields you tend to filter on (sounds like Timestamp) -- that should speed it up quite a bit.

We recently added the ability to specify indexes to create in the config, but it hasn't been bundled in a release yet.  In the future we'd also like to include some historic aggregation options, but we aren't there yet.

**Comment by jmangue** [comment]
Another idea to speed up the view would be to schedule some kind of database task to drop data older than a certain threshold, depending on your retention needs.

Using Tableau to create an extract is also an option.

**Comment by spookymonster** [comment]
So Tabmon doesn't clean up old records? Is this mentioned anywhere in the
documentation? What other maintenance does it require on a regular basis?

**Comment by jmangue** [comment]
That's correct.  TabMon does not delete old data; curation of data it generates is left up to the user, although we do have a feature request to add a configuration flag to purge data older than a certain threshold.  Issue #13 

Since it seems like a point of confusion, I'll spin up an Issue to update the documentation to explicitly state that TabMon does not delete data.

**Comment by jmangue** [comment]
Opened up Issue #43 to address this.  Thanks for the suggestion.

Oh, and other than managing data retention, I can't think of any other maintenance that is required on a regular basis.

**Comment by spookymonster** [comment]
Thanks Justin. This can cause a big problem for admins that have little or
no database management experience, or are unfamiliar with pgadmin3. Letting
people know upfront that this isn't a push-button setup will prepare them
for the additional time and resources required to maintain the app.

**Comment by jmangue** [comment]
Closing this issue out since the work items are tracked in #43 and #13
