### ISSUE TITLE
Connecting to CSV

### ISSUE THREAD

**Issue by jostnasrinivas** [tableau/TabMon#44]
Hi,

I want to connect to CSV instead of db. for that I have modified the config file accordingly and opened the workbook and connected to the flat file stored in the results folder. but the workbook is still asking DB credentials and data source displayed is DB. can some one help me on how to connect to csv and pull data from flat files.

**Comment by jostnasrinivas** [comment]
Can anyone help me out on this.
As instructed in the installation guide, I have changed the config file to csv. the result is stored to the results folder. But when open the workbook, it still asks me for the output DB password and still gets connected to the o/p DB.

**Comment by yurifal** [comment]
Hi @jostnasrinivas,

Please do the following:

1) Make a copy of your TabMonWorkbook.twb

2) Open this copy (keep original safe).

3) When prompted for a PG login, select Cancel.

4) Connect to your CSV as a new datasource.
Select Data --> New Datasource --> Text 
and point to a directory ..\Tabmon\Results

There could be a file named counteresamples.csv
Drop it to the data schema panel (a top right area).

5) Return to a current view. 
Right-click to the TabMon datasource 
and choose **Replace Datasource** --> 
choose your new CSV-based datasource 
(aka "countersamples") as a replacement. 
When done, your new DS become a Primary 
for the current view (blue mark) and all views 
which is based on a TabMon DS in the original wb.

6) Check if your datasource schema for fields with ! mark on the left.
If everything is OK, there should be no one such a field.

7) Save your wb, and you've done.

When working with CSV-based datasources, 
Tableau creates an extract in the background.
So to refresh a view, one could press F5 sometimes.

Hope this could help.

Yours,
Yuri

**Comment by jmangue** [comment]
Yuri,  thanks for helping out!

We also have a KB article on how to do this kind of thing in general, in case it helps: http://kb.tableau.com/articles/knowledgebase/replacing-data-source

**Comment by jmangue** [comment]
jostnasrinivas did you get this issue resolved?

**Comment by jostnasrinivas** [comment]
Thanks guys for the steps. But I am facing the following issue on all viwes. data is not being populated.

All the views shows 0 data with a horizontal line.
![1](https://cloud.githubusercontent.com/assets/17403965/13521727/bacad674-e210-11e5-935f-1710ac665a8a.png)
![2](https://cloud.githubusercontent.com/assets/17403965/13521729/bfe39484-e210-11e5-8aa6-25131af261e6.png)
I want to wit and see for few more hours and connect to new file that will be generated.

**Comment by jmangue** [comment]
jostnasrinivas, from your two views, the first is only showing a single data point and the second is showing data correctly being there.  Once you waited for more time did your data start showing up properly?

**Comment by jmangue** [comment]
Closing out due to inactivity, please reopen if you still need help.
