### ISSUE TITLE
issue while creating extract

### ISSUE THREAD

**Issue by jostnasrinivas** [tableau/TabMon#45]
Hi,

I am getting following error when trying to create extract.

"The extract has a different time zone from underlying server. Calculations using today() NOW() and relative data filters give different data"

Please help me to create the extract

**Comment by yurifal** [comment]
Hi @jostnasrinivas, 

It looks like you've created the extract anyway :-)
The message you gave from Tableau Desktop 
is not an error one, but rather a gentle warning.

It indicates that the underlying DBMS has 
a different time zone settings than Tableau Data Engine, 
hence a warning. But the extract has been created already.

Hope this could help.

Yours,
Yuri

**Comment by jostnasrinivas** [comment]
HI Yuri,

Yup... now I doubt will there be any issue with data?

**Comment by yurifal** [comment]
Nope, in general.

If you’re using Relative Date Filter 
or a calc with TODAY() or NOW() functions 
then results may differ when using 
either Extract or Live Connection to DS.

Yours,
Yuri

**Comment by yurifal** [comment]
If you’re sure your Tableau Desktop 
(or Tableau Server which hosts a workbook) 
is in the same time zone as your DBMS host, 
then don’t worry about it.

**Comment by jostnasrinivas** [comment]
I need to check.. Will make a check and get back on this. What is the work around to be performed if they both are in different time zones.?

**Comment by yurifal** [comment]
You would like to create a calculated field (say [Date TZ] )
to compensate for a n-hour difference between hosts time zones.

http://kb.tableau.com/articles/issue/warning-time-zone-differences

Yours,
Yuri

**Comment by danjrahm** [comment]
Thanks for the comment Yuri! That's the exact advice I would pass. 

I'm going to close this comment out.
