### ISSUE TITLE
Getting the following error when recording with tabmon - JMX counters

### ISSUE THREAD

**Issue by VenkMyla** [tableau/TabMon#47]
Using tabmon for the first time and having issues with it. I am seeing the following information in the logs :016-02-26 22:04:48,748 [6] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\zusc-s-tsttbl02\vizportal\tableau.health.jmx:name=webclientappservice.login\RequestsFailed\vizportal: Unable to query MBean.
2016-02-26 22:04:48,748 [6] DEBUG TabMon.Counters.MBean.AbstractMBeanCounter - Error sampling counter Primary\zusc-s-tsttbl02\vizportal\tableau.health.jmx:name=webclientappservice.login\RequestsProcessed\vizportal: Unable to query MBean.

**Comment by jmangue** [comment]
Did you enable JMX ports on Tableau Server?

**Comment by agreenhaw** [comment]
I am experiencing the same issue and have enabled JMX ports on our primary node. We've got service.jmx_enabled: true in our YML file. We are still getting data in the results file and can connect it to the sample workbook so this wasn't sure if this was of concern. Do these errors indicate that there is an actual issue with the Tabmon deployment that should be resolved?

Thanks,
Angie Greenhaw

**Comment by jmangue** [comment]
If you're getting some JMX data and are just missing the counters that have "webclientappservice" in their path, and are not on Tableau Server 9.1 or later... please check out the FAQ section of the user guide, under "TabMon is not collecting several of my JMX counters".  It contains the Counters.config setting you'll need to properly retrieve those counters.

**Comment by VenkMyla** [comment]
Yes, that resolved the issue. My tabmon is up and running now.. Thanks jmangue for your help. The tip was very helpful.
