### ISSUE TITLE
Blank Network Sheet

### ISSUE THREAD

**Issue by danjrahm** [tableau/TabMon#49]
Hello Team,
we installed Tabmon on our environment (version 9.0). but while validating data we are getting blank for Network sheet and we have null values for measures present on dashboard.

Kindly Help me to fix the issue.

Thanks
Manoj

**Comment by danjrahm** [comment]
Hello Manoj,

I am not 100% sure what is causing the blank network sheet. To look into this please send me the logs (TabMon.log) from the TabMon folder. The default file path is C:\Program Files (x86)\TabMon\Logs.

Thanks,
Dan

**Comment by jmangue** [comment]
This is probably a manifestation of Issue #22

**Comment by ManoSahoo165** [comment]
[TabMon.log.txt](https://github.com/tableau/TabMon/files/163353/TabMon.log.txt)

Hello Danjrahm,
Please find attached log file as requested.

Thanks in advance to look into the request.

Thanks
Manoj

**Comment by danjrahm** [comment]
It looks like no network data is being collected because the JMX counters that it is looking for do not exist. What version of Tableau Server are you on? 

We're looking into this now.

**Comment by jmangue** [comment]
Hi Manoj,

Yeah -- the missing network data is due to a known bug (#22) that we are tracking.  We are planning a fix and will prioritize it higher since it's hitting an additional user.  Sorry for the troubles.

**Comment by ManoSahoo165** [comment]
Hello,
We tried tableau version 9.2.
Thanks
Manoj

**Comment by ManoSahoo165** [comment]
Kindly let me know once you will have update on mentioned issue..?

**Comment by ManoSahoo165** [comment]
Hello Team,
Please let me know once you have update on mentioned issues.?

Thanks
Manoj

**Comment by jmangue** [comment]
Hi Manoj -- as I mentioned above, this is a known bug (#22).  If you click on that issue you can subscribe to notifications for when it is resolved.

**Comment by ManoSahoo165** [comment]
Hello team,
Do we have any update on same issue or still you are working on that request..?

Thanks
Manoj

**Comment by jmangue** [comment]
Closing this issue out in favor of #22 to avoid duplication, for updates you can see that issue.
