### ISSUE TITLE
Stop Tabmon Not Working

### ISSUE THREAD

**Issue by agreenhaw** [tableau/TabMon#50]
Hello,

I am able to start Tabmon on our primary Server node, but when I try to stop it (by clicking on the Stop tabmon app in the UI with "Run as Administrator" the service continues to show as running in Task Manager. Is it better to just stop the service in the Services tab of Task Manager? What is the recommended approach? 

Thanks,
Angie Greenhaw

**Comment by jmangue** [comment]
Neither approach is recommended over the other, as both achieve the same goal; all the shortcut in the start menu does is call _net stop "TabMon"_ to stop the service.   The "TabMon-Postgres" service is intended to stay running in both situations.  It's interesting that the shortcut isn't appearing to work for you; I'd probably guess permissions are at play.

**Comment by jmangue** [comment]
Closing this out due to inactivity.
