### ISSUE TITLE
Wanted clarification on Postgres processes

### ISSUE THREAD

**Issue by rishabh1991** [tableau/TabMon#51]
HI,

Can you please let me know there are nearly 70 postgres processes running on my TabMon.
what do they exactly mean.
![capture](https://cloud.githubusercontent.com/assets/17762245/13740028/88163b24-e9f4-11e5-905d-c297433e3797.PNG)

**Comment by russch** [comment]
Unlike a database like SQL Server which handles all requests using a single process, PostgreSQL spawns a new postgres.exe to handle each connection. You're just seeing that particular database's normal behavior. 

From  http://www.postgresql.org/docs/current/interactive/tutorial-arch.html : 

The PostgreSQL server can handle multiple concurrent connections from clients. To achieve this it starts ("forks") a new process for each connection. From that point on, the client and the new server process communicate without intervention by the original postgres process. Thus, the master server process is always running, waiting for client connections, whereas client and associated server processes come and go. (All of this is of course invisible to the user. We only mention it here for completeness.)

**Comment by jmangue** [comment]
Yep, this is expected as Russell mentioned.  Closing this out; let us know if you have any more questions.
