### ISSUE TITLE
TabMon Service not starting

### ISSUE THREAD

**Issue by imtiyazms** [tableau/TabMon#53]
Hi Team,
I am struggling to make TabMon work on our machines. Everytime ending up with the same issue
Error 5: Access is denied.
Kindly please look into the issue and let me know what steps should I take to make it work.

OS : Windows Server 2008 R2
Followed thread https://github.com/tableau/TabMon/issues/9, did clean installation of TabMon but still no use.

Log files
---------------------
TabMon.log.txt
-----------------------
2016-03-15 23:53:05,420 [5] INFO TabMon.Config.TabMonConfigReader - Loading TabMon user configuration..
2016-03-15 23:53:05,471 [5] DEBUG TabMon.Config.TabMonConfigReader - Loading database configuration..
2016-03-15 23:53:05,473 [5] INFO TabMon.Config.TabMonConfigReader - Connecting to results database..
2016-03-15 23:53:05,600 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: FATAL: 28P01: password authentication failed for user "tabmon"
2016-03-15 23:53:05,602 [5] DEBUG TabMon.Helpers.HostnameHelper - Successfully resolved 'localhost' to 'ENGTBLVM01-STG'.
2016-03-15 23:53:05,609 [5] FATAL TabMon.Config.TabMonConfigReader - Invalid options in configuration: [Host='Primary\ENGTBLVM01-STG', Writer='null', PollInterval='30', TableName='countersamples']
2016-03-15 23:53:05,610 [5] INFO TabMon.TabMonAgent - Initializing TabMon..
2016-03-15 23:53:05,610 [5] FATAL TabMon.TabMonAgent - Invalid TabMon options specified!
Aborting..
2016-03-15 23:53:05,610 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
--------------------------------
DBCreation.log
------------------------------
Ok.

The files belonging to this database system will be owned by user "SYSTEM".
This user must also own the server process.

The database cluster will be initialized with locale "English_United States.1252".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory C:/Postgres/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... windows
creating configuration files ... ok
creating template1 database in C:/Postgres/data/base/1 ... ok
initializing pg_authid ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... not supported on this platform
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    "C:\Postgres\bin\postgres" -D "C:\Postgres\data"
or
    "C:\Postgres\bin\pg_ctl" -D "C:\Postgres\data" -l logfile start

restart-service : Failed to start service 'TabMon-Postgres (TabMon-Postgres)'.
At C:\Program Files (x86)\TabMon\PGSetup.ps1:29 char:1
+ restart-service $ServiceName *>> $LogDir\DBCreation.log;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Restart-Service], ServiceC 
   ommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.RestartServiceCommand
 
.\createdb : createdb: could not connect to database template1: fe_sendauth: no password supplied
At C:\Program Files (x86)\TabMon\PGSetup.ps1:33 char:1
+ .\createdb --port=$Port --username=$SuperUser --owner=$SuperUser --no-password $ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (createdb: could...ssword supplied:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
.\psql : psql: fe_sendauth: no password supplied
At C:\Program Files (x86)\TabMon\PGSetup.ps1:34 char:1
+ .\psql --dbname=$DBname --username=$SuperUser -w --port=$Port --command="CREATE  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (psql: fe_sendauth: no password supplied:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
restart-service : Failed to start service 'TabMon-Postgres (TabMon-Postgres)'.
At C:\Program Files (x86)\TabMon\PGSetup.ps1:41 char:1
+ restart-service $ServiceName *>> $LogDir\DBCreation.log;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Restart-Service], ServiceC 
   ommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.RestartServiceCommand
 

Regards,
Imtiyaz

**Comment by russch** [comment]
The errors indicate that TabMon can't connect to PostGre:

Connecting to results database..
2016-03-15 23:53:05,600 [5] FATAL TabMon.Config.TabMonConfigReader - Could not initialize writer: FATAL: 28P01: password authentication failed for user "tabmon"

Further into the log, it looks like the automatic installation of PosgreSQL didn't go well. Perhaps you can uninstall TabMon and PostgreSQL, then manually install PostGreSQL from here:http://www.enterprisedb.com/products-services-training/pgdownload 

After that, follow the instructions around how to use TabMon with an existing instance of PostgreSQL.

**Comment by jmangue** [comment]
Closing this out.
