### ISSUE TITLE
Having Trouble Accessing Tabmon

### ISSUE THREAD

**Issue by ajones1330** [tableau/TabMon#6]
You probably have gotten this before, but I am trying to use TabMon to monitor the performance of my Tableau Server. When trying to login to "localhost" with the database "TabMon" and the default username and password, tabmon and "password" respectively. I get the following error. I am so excited about using this. I hope I left a detailed enough description of my issue. 
![image](https://cloud.githubusercontent.com/assets/11967628/10741965/d835dde2-7be7-11e5-9854-367830e4a5d0.png)

**Comment by benedictchan886** [comment]
The table in my setups Tabmon.countersamples. How did you do the installation?

**Comment by jmangue** [comment]
The "countersamples" table is created the first time you start up the service; if it doesn't exist, then there was some problem starting TabMon.

The most common cause for this is a permissions issue when running the "Start TabMon" shortcut.  Try right-clicking on "Start TabMon" and selecting "Run As Administrator".  Once that's done, if you go into "Services.msc" and look at the list of services, the "TabMon" service should be in a "Running" state and you should then be able to load the workbook.  If it still isn't "Running", then unfortunately there is something else going on which will require digging into the TabMon logs.

**Comment by jmangue** [comment]
Also -- as benedictchan886 mentioned, how did you do the installation?  Did you leave the "Install Postgres for me" box checked?

**Comment by danjrahm** [comment]
If jmangue's suggestions do not work can you attach the DBCreation.log file? You should be able to find this file in the temp directory.

**Comment by danjrahm** [comment]
Hello,

I just wanted to see if you were able to get TabMon running.

Thanks,
Dan

**Comment by danjrahm** [comment]
Closing this. If the issue persists or there are any other issues let me know.

**Comment by SrujanYada** [comment]
I installed tabmon few minutes back and when trying to access the tabmon workbook, got the error as mentioned in this thread. can you please suggest what the error is?
![capture](https://cloud.githubusercontent.com/assets/16767471/12405245/cc9d9d1e-be07-11e5-8c00-34c0d9e5c41c.PNG)
I also tried to check for dbcreation log.. couldnt find one. there is a tabmon log.
also, when i tried to start & stop tabmon.. a CSV file was generated but most of the counters were null. please suggest.

**Comment by benedictchan886** [comment]
Have you installed Postgres when you installed Tabmon?

And have you started up postgres? like

> cd C:\Postgres\bin

C:\Postgres\bin>pg_ctl start -D "C:\Postgres\data"

**Comment by SrujanYada** [comment]
Yes.. have installed postgres and I see it is started in services.

[cid:image001.png@01D1522A.60057710]

Regards,
Srujan

**Comment by benedictchan886** [comment]
Let's do this

Do you see something similar?

1. See if the TabMon database there

C:\Postgres\bin>psql -U tabmon -l
                                                           List of databases
   Name    |      Owner      | Encoding |          Collate           |           Ctype            |          Access privileges
-----------+-----------------+----------+----------------------------+----------------------------+-------------------------------------
 TabMon    | tabmonsuperuser | UTF8     | English_United States.1252 | English_United States.1252 |
 postgres  | tabmonsuperuser | UTF8     | English_United States.1252 | English_United States.1252 |
 template0 | tabmonsuperuser | UTF8     | English_United States.1252 | English_United States.1252 | =c/tabmonsuperuser                 +
           |                 |          |                            |                            | tabmonsuperuser=CTc/tabmonsuperuser
 template1 | tabmonsuperuser | UTF8     | English_United States.1252 | English_United States.1252 | =c/tabmonsuperuser                 +
           |                 |          |                            |                            | tabmonsuperuser=CTc/tabmonsuperuser
(4 rows)


2. Let's see what tables inside the TabMon db

C:\Postgres\bin>psql -U tabmon -d TabMon
psql (9.4.4)
WARNING: Console code page (437) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
Type "help" for help.

TabMon=> \d+
                               List of relations
 Schema |         Name          |   Type   | Owner  |    Size    | Description
--------+-----------------------+----------+--------+------------+-------------
 public | countersamples        | table    | tabmon | 2771 MB    |
 public | countersamples_id_seq | sequence | tabmon | 8192 bytes |
(2 rows)

**Comment by SrujanYada** [comment]
I was not able to find any relations ☹

[cid:image001.png@01D15239.2A6216E0]

**Comment by benedictchan886** [comment]
There are 3 parts.

1. Postgres (installed during Tabmon installation) to store the performance data.
2. Tabmon executable (service), that's the process to go writing into the Postgres
3. The workbook, connecting to Postgres to show it in the viz.

Your error seems that it cannot find the table that stores the data. So, the previous steps are to show what you really have in your Postgres

**Comment by SrujanYada** [comment]
I have just executed the tabmon executable as mentioned in the user guide. Why would it not create the tables to store the performance data? What can we do to fix this please?

**Comment by benedictchan886** [comment]
Back one step first, do you see the TabMon database and countersamples table in your Postgres?

**Comment by SrujanYada** [comment]
I couldn’t find the tables in the database.

[cid:image001.png@01D15294.817BD9B0] [cid:image002.png@01D15294.817BD9B0]

**Comment by SrujanYada** [comment]
![capture1](https://cloud.githubusercontent.com/assets/16767471/12421461/066e06b6-be88-11e5-933b-c3106b8468b9.PNG)
![capture2](https://cloud.githubusercontent.com/assets/16767471/12421462/0685cb70-be88-11e5-9055-b630d95b2fc3.PNG)

**Comment by SrujanYada** [comment]
I earlier tried to install tabmon with "Install and initialize postgres for me" option checked on our tableau server. When i check for the tables in tabmon database after the install is completed, i see no relations displayed.

can you please suggest on how to proceed? I see there is an issue with postgres install. Do we need to uninstall and install again? Will there be any impact to existing postgres tableau database?

**Comment by benedictchan886** [comment]
Would you please check if there is any error in C:\Temp\DBCreation log?

**Comment by SrujanYada** [comment]
By the way, thanks for all your support. I was able to uninstall/reinstall successfully.

**Comment by benedictchan886** [comment]
Is it resolved now? Srujan

**Comment by SrujanYada** [comment]
Yes. It is resolved. I started tabmon yesterday and was able to see results now on the workbook. However, I do not see network related metrics. Checking whats wrong..

**Comment by jmangue** [comment]
Glad its up and running!

The missing network data *may* be due to Issue #22 , we have heard of one other user with the same issue.
