### ISSUE TITLE
How to check which workbooks causing more CPU utilization on the server?

### ISSUE THREAD

**Issue by spokala** [tableau/TabMon#61]
If I see more CPU consumption or Memory consumption for specific period of time, I want to check which workbooks were causing this issue? Do we have a way to check this using tabmon workbook? 
If yes, please let me know the steps how to do that?

**Comment by danjrahm** [comment]
TabMon may be able to see what is going on using the 'What's Going On?' dashboard, but this will be fairly limited. In order to use the 'What's Going On?' dashboard, the readonly user will need to be set in Tableau Server.
http://onlinehelp.tableau.com/current/server/en-us/help.htm#adminview_postgres_access.htm

My preferred method for looking into what workbooks are loading at that time is to parse the apache logs using regex and write it out to a txt file or csv. Once in that format it can be used as a data source in Tableau Desktop.

Another method is to use the apache logs as a datasource directly and use the split functionality in Tableau Desktop to make the logs readable.

If there are any other questions let me know.

**Comment by spokala** [comment]
HI Dan..
Thanks for your previous reply...
I created readonly user and I was able to acces what's going on dashboard with out any issues...

But My requirement is to identify the workbooks which were ran during high CPU utilization or memory consumption peroid... with following information.
1. Work Book Name.
2 Execution Time 
3. if possible which workbook consumed more resources....


Few questions:
Apache logs are nothing but tableau server log files and which were generated using  tabadmin ziplogs.? Is this true?

Please let provide me more information how to get above information?

**Comment by tfoldi** [comment]
Hello Spokala,

This is exactly what Palette Insight is doing, getting CPU utilization over time per workbook. This is the only product that can do this: http://palette-software.com/

TabMon is far away from this at the moment, but it's free at least.

**Comment by danjrahm** [comment]
Hello Spokala,

To answer your question, the apache logs are not generated using tabadmin ziplogs. The command 'tabadmin ziplogs' packages all of our log files into a zipped folder. The logs themselves can be accessed without using the ziplogs command.

For Tableau Server environments where Tableau Server is installed on the C:\ drive (default install location), the Apache logs can be found here: C:\ProgramData\Tableau\Tableau Server\data\tabsvc\logs\httpd

To analyze what workbooks are running during periods of high CPU usage, I recommend opening the 'access*.log' files in Tableau Desktop using one of the methods I mentioned earlier. Once the logs are parsed in Tableau Desktop, I would look for any requests with 'bootstrapSession' in the message body; this indicates a the start of a workbook load. A filter for finding 'bootstrapSession' can be found using a 'contains' calculated field.

As for tfoldi's response, they are correct. This sort of functionality is outside the scope of TabMon. 

The analysis can be done, but it will be a bit more complicated. 

Thanks,
Dan

**Comment by jmangue** [comment]
Closing as answered.

**Comment by john-abdo** [comment]
Hello Spokala

Tableau Workbook CPU consumption reporting is only possible with our [Palette Chargeback](http://palette-software.com/) add-on for Tableau Server. With Palette Chargeback, you can see both CPU usage (reported as CPU seconds) as well as with a CPU/Hour cost multiplier for socializing resource consumption with regular business users.

In addition to workbook CPU, you can also report by user, project, or site as well as down to the individual user session with that specific workbook, so you always have the underlying detail for justifying your summary chargeback numbers.

You can check out a real but anonymized version of our report in a [Palette Chargeback dashboard](https://public.tableau.com/views/PaletteChargeback/OVERVIEW?:embed=y&:display_count=yes) that we have published to Tableau Public.

![palette chargeback screenshot workbook cpu usage and cost](https://cloud.githubusercontent.com/assets/14877759/19841162/4b85e27a-9ec3-11e6-9564-61da0ab52344.png)

Best regards,
John Abdo
CEO+Founder, Palette Software
john@palette-software.com
[palette-software.com](http://palette-software.com)

**Comment by naveentalari** [comment]
Hi All,

How to open access.log file in Tableau Desktop?

Can anyone please elabrote this process.

Thanks,
Naveen

**Comment by arunyadav19** [comment]
@john-abdo ,is there any way I can download this chargeback dashboard twbx ?
