### ISSUE TITLE
Missing Fields on TabMon DataSource

### ISSUE THREAD

**Issue by joseasalazar83** [tableau/TabMon#62]
Hi 
I installed TabMon on a Windows Server 2012 R2 server, and when I am trying to check the dashboards on TabMonWorkbook, I noticed that there are many missed fields in the TabMon datasource. Due this issue, obviously many of dashboards does not show information.

Here is a list with some of the missing fields 
1.- active_sessions
2.- average_batch_failure
3.- average_batch_size
4.- average_batch_latency
5.- average_request_latency
6.- External Abstract Query Hit Ratio
7.- External Abstract Query Hit Ratio
8.- External Abstract Query Hit Ratio
9.- external_abstract_query_cache_misses
10.- external_abstract_query_cache_misses

Notes
1.- TabMon appears is working OK.
2.- I'm using Tableau Desktop 9.2.6 to open the workbook.

Attached Images:
![tabmon_poolingprocess](https://cloud.githubusercontent.com/assets/18536596/14614051/f950e3b2-0564-11e6-9f0b-0c9b3df34449.PNG)
![tabmon_missedfields](https://cloud.githubusercontent.com/assets/18536596/14614050/f94f8cc4-0564-11e6-99f6-c74375a7d680.PNG)

Do you know why I have these missing fields?

I would appreciate any help.

Best Regards
José Alberto

**Comment by russch** [comment]
Hey Jose.  This is a know problem detailed in issue 55. In essence,  many of the JMX MBeans which TabMon polls for information have been moved (or their names have changed)  in 9.3

**Comment by joseasalazar83** [comment]
Hi Sussch. 
Thanks for reply so quickly. I noticed that I forgot to enable the JMX ports.
Thanks again.

Regards.

**Comment by jmangue** [comment]
Closing this out in favor of https://github.com/tableau/TabMon/issues/55
