### ISSUE TITLE
Feature Request: Ability to to only store data in postgres once performance thresholds are hit. 

### ISSUE THREAD

**Issue by paolomoran** [tableau/TabMon#66]
One of my customers has requested a feature that would force tabmon to only store data in postgres once performance metrics such as CPU and RAM exceed 70% usage. The reason for this Feature Request is that the customer does not want to use up too much space in their Postgres Database and they find that having data on when performance metrics exceed a threshold is more useful to them.

**Comment by jmangue** [comment]
Good idea, thanks for sharing!  Setting this as an enhancement idea.

**Comment by jmangue** [comment]
I'm going to close this as a "won't fix" as it's out of scope for the time being.  

In #92 we introduced a data retention threshold and a new condensed data model which will should help prevent the disk usage from getting out of hand.  If they want more granular control over what data is kept, they could try using Postgres triggers.
