### ISSUE TITLE
VC++ Runtime merge module Issue

### ISSUE THREAD

**Issue by varun7447** [tableau/TabMon#67]
DBInitializerr project works? I am facing issues with the PGSetup1 being executed before the VC++ mergemodule in the project.

**Comment by jmangue** [comment]
Interesting... the VC++ merge module should be happening prior to execution of the PGSetup script.  I assume this is causing install to fail?

**Comment by varun7447** [comment]
Yes, one interesting thing I noticed is. Actually I am running tabmon in my desktop. When I run the VC++ redist 64 version exe it is working totally fine may be the VC++ merge module is ignored and PGSetup script is running fine because of the manual installation of VC++ x64 redist

**Comment by jmangue** [comment]
Glad to hear it is working... closing this one out, please reopen if you have any more issues!
