### ISSUE TITLE
Tabmon Postgres DB running out of space

### ISSUE THREAD

**Issue by Tabuser** [tableau/TabMon#69]
Hi,

We have postgres db related to tabmon installed on one of the physical drives in Tableau primary node. Since it polls the data every 30 sec into the db, we are running into space issues.
Here are my questions.
1. How do we change the poll interval for 3600 sec.
2. How do I change the directory of the tabmon postgres?

Any quick help on this is appreciated.

Thanks

**Comment by russch** [comment]
tabmon.config allows you to change the poll interval. 

There is no "automatic" way to move Postgres. You'll likely need to do some research on your own around the smartest way to do this. You certainly backup the database with pgadmin3, uninstall postgres, and then re-install it to a different directory (applying the backup afterwards), but I suspect there is a faster / smarter way if you look around a little.
