### ISSUE TITLE
Unable to Load 'Latency' view from Worker machine

### ISSUE THREAD

**Issue by siddharthsurana** [tableau/TabMon#71]
Hey Guys, I was able to successfully install this in my distributed env (Kudos for this work btw). 16 core set up - 12 Primary, 4 worker (Backgrounder only) . The set up was smooth and most views in the dashboard are being populated for both the primary and the worker machine, except for the "Thread Count" & the "Latency" dashboard data for the worker. Would you happen to know why?

**Comment by russch** [comment]
Based on the version of Tableau Server you're running, some of the "counter names" have actually changed. TabMon is asking for counters (called MBeans) that don't exist, and these vizzes use those counters (which are currently returning NULL). Expected at this point.

**Comment by siddharthsurana** [comment]
Thanks @russch We are  on the latest server version (9.3.1). Is this something I can change on my end? Also, loving the vizzes. Cant stop monitoring now!

**Comment by russch** [comment]
The only thing you can do (without changing TabMon code yourself) is stop monitoring these counters.

**Comment by jmangue** [comment]
https://github.com/tableau/TabMon/issues/55 is open to address fixing this.  Closing this one out.
