### ISSUE TITLE
How to delete or recreate the database TABMON

### ISSUE THREAD

**Issue by Shobananpa** [tableau/TabMon#74]
Hi Team,

I'm looking for help to delete and recreate the database for tabmon.
I'm seeing this error.
The description for Event ID 0 from source PostgreSQL cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

ERROR:  database "TabMon" already exists
STATEMENT:  CREATE DATABASE "TabMon" OWNER tabmonsuperuser;

Can someone help me to delete and recreate and proceed with my installation.

Thanks,
Shoba

**Comment by jmangue** [comment]
Answered via email -- but I'll restate here in case it helps anyone else out...

Instructions for removing the DB are found in the “Uninstalling Tabmon & Postgres” section on page 9 of the user guide. https://github.com/tableau/TabMon/blob/master/TabMonService/Documentation/UserGuide.pdf  If you follow the instructions in the guide, you should not see those errors.  Basically, you just need to uninstall TabMon, stop & delete the TabMon-Postgres service and then delete the Postgres folder. 
 
At that point, you should be able to reinstall TabMon with Postgres to get everything back in a good state.  Or you can follow the manual Postgres database setup instructions (also in the user guide).

**Comment by Shobananpa** [comment]
Justin, 

I tried all the steps mentioned in the installation guide to stop and delete postgres, Uninstall tabmon and deleted postgres folders. 
Stull I'm unable to run tabmon post reinstallation

**Comment by jmangue** [comment]
What problem are you seeing now that you've removed & reinstalled everything?
