### ISSUE TITLE
Number of active sessions is negative

### ISSUE THREAD

**Issue by thecoderok** [tableau/TabMon#77]
In the workbook received from existing installation I see that number of active sessions is negative.
When I look at domain of the active_sessions measure I see negative number:

![negative_domain](https://cloud.githubusercontent.com/assets/3173477/17034303/effb3256-4f36-11e6-97e2-fd6a7335e5fb.png)
![total_sum](https://cloud.githubusercontent.com/assets/3173477/17034306/f71073a8-4f36-11e6-8610-c3eb97e6c0b0.png)

In my understanding, number of active sessions can't be negative.

**Comment by danjrahm** [comment]
Hello, 

The active_sessions number should correspond to the number of session creation and destruction events within Tableau Server. The positive numbers correspond to the creation of a session while the negative numbers correspond to the session destruction events. 

Any time a negative number is seen in this field it should be interpreted as a session timing out and being reaped. 

If there are any other questions let me know. Until then, I am going to close this issue.
