### ISSUE TITLE
Error with Countersamples

### ISSUE THREAD

**Issue by sridhar83** [tableau/TabMon#8]
![capture](https://cloud.githubusercontent.com/assets/12438517/10791240/dd19a6fa-7d5d-11e5-9dc3-208bcb11188b.PNG)

Installation went smooth, made all the necessary changes to Tabmon.config file, and Tabmon services are started but countersamples table is not present.

**Comment by danjrahm** [comment]
Hello,

It looks like TabMon is not properly writing to the Postgres table. Can you please attach the TabMon.log file?

This can be found in the Logs directory of the TabMon folder.

**Comment by danjrahm** [comment]
Looking into this a bit further it looks like you are connected to the Tableau Server workgroup database but not the TabMon database. 

After opening the workbook, when prompted to edit the connection information, what information was entered into the window?

Try using the information below.
Server: localhost
Port: 5432
Database: TabMon
Username: tabmon
Password: password

This information should work as long as TabMon was installed on the Tableau Server machine and the information in the options menu was not edited.

**Comment by sridhar83** [comment]
Thank you so much for your reply!
I will certainly follow your instructions and try it out.
I will keep you posted for any updates.

Thanks
