### ISSUE TITLE
TabMon Counters

### ISSUE THREAD

**Issue by SriVV** [tableau/TabMon#85]
We are using ver 9.3.1 and have TabMon installed and configures. We see that counters.config is using "webclientappservice" as expected in new versions and we have opened JMX ports as per the install guide.

We see a a lot of information being logged but the counter_type is always 'Perfmon', can you confirm if this is the only counter_type expected as out of the box ?? 

I see counters.config which has perfmon defined. Has anyone defined any other counters

Thanks

**Comment by jmangue** [comment]
Hi SriVV,

There are three different types of "counter_type" that can appear: "PerfMon", "JVM Health", and "Tableau Server Health".  The latter two come from the JMX counters.  These are defined in the bottom half of Counters.Config under the "MBean" element.

**Comment by SriVV** [comment]
Hi jmangue,

We have below configuration in counters.config. looks like we have this in place but i don't see any data in the separate postgress database we configured for Tabmon ?? 

I see below in log file but no reference to jmx ports, any pointers that can help us poll for JVM and Tableau server ?? All referenced ports are open on all servers

2016-08-15 15:30:34,730 [12] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Prod\servername\Perfmon\Process\% Processor Time\tdeserver64#3: Instance 'tdeserver64#3' does not exist in the specified Category.
2016-08-15 15:30:35,261 [12] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Prod\servername\Perfmon\Process\Working Set\tabprotosrv#7: Instance 'tabprotosrv#7' does not exist in the specified Category.


Conunters.config file

 <MBean>
    <Source name="vizportal" startport="8900" endport="8999">
      <TableauHealth>
        <Category name="Get View" path="name=webclientappservice.getview">
          <Counter name="AverageRequestLatency" unit="ms" />
          <Counter name="RequestsFailed" />
          <Counter name="RequestsProcessed" />
        </Category>
        <Category name="Guest Login" path="name=webclientappservice.guestlogin">
          <Counter name="AverageRequestLatency" unit="ms" />
          <Counter name="RequestsFailed" />
          <Counter name="RequestsProcessed" />
        </Category>
        <Category name="Publish Workbook" path="name=iclientxmlappservice.publishworkbook">
          <Counter name="AverageRequestLatency" unit="ms" />
          <Counter name="RequestsFailed" />
          <Counter name="RequestsProcessed" />
        </Category>
        <Category name="Run Extract Tasks" path="name=webclientappservice.runextracttasks">
          <Counter name="AverageBatchFailure" />
          <Counter name="AverageBatchSize" />
          <Counter name="AverageRequestLatency" unit="ms" />
          <Counter name="RequestsFailed" />
          <Counter name="RequestsProcessed" />
        </Category>
        <Category name="Run Extract Refreshes on Workbooks" path="name=webclientappservice.runextractrefreshesonworkbooks">
          <Counter name="AverageBatchFailure" />
          <Counter name="AverageBatchSize" />
          <Counter name="AverageRequestLatency" unit="ms" />
          <Counter name="RequestsFailed" />
          <Counter name="RequestsProcessed" />
        </Category>
        <Category name="Run Extract Refreshes on Data Sources" path="name=webclientappservice.runextractrefreshesondatasources">
          <Counter name="AverageBatchFailure" />
          <Counter name="AverageBatchSize" />
          <Counter name="AverageRequestLatency" unit="ms" />
          <Counter name="RequestsFailed" />
          <Counter name="RequestsProcessed" />
        </Category>
        <Category name="Run Schedules" path="name=webclientappservice.runschedules">
          <Counter name="AverageBatchFailure" />
          <Counter name="AverageBatchSize" />
          <Counter name="AverageRequestLatency" unit="ms" />
          <Counter name="RequestsFailed" />
          <Counter name="RequestsProcessed" />
        </Category>
        <Category name="Search Metrics" path="name=searchservice">
          <Counter name="AverageQueryLatency" unit ="ms" />
          <Counter name="RequestProcessed" />
        </Category>
        <Category name="Sync AD Group" path="name=iclientxmlappservice.syncactivedirectorygroup">
          <Counter name="AverageRequestLatency" unit="ms" />
          <Counter name="RequestsFailed" />
          <Counter name="RequestsProcessed" />
        </Category>
        <Category name="User Login" path="name=webclientappservice.login">
          <Counter name="AverageRequestLatency" unit="ms" />
          <Counter name="RequestsFailed" />
          <Counter name="RequestsProcessed" />
        </Category>
      </TableauHealth>
      <JVMHealth>
        <Category name ="Compilation" path="type=Compilation">
          <Counter name="TotalCompilationTime" unit="ms" />
        </Category>
        <Category name="Memory" path="type=Memory">
          <Counter name="HeapMemoryUsage\committed" unit="bytes" />
          <Counter name="HeapMemoryUsage\used" unit="bytes" />
          <Counter name="NonHeapMemoryUsage\committed" unit="bytes" />
          <Counter name="NonHeapMemoryUsage\used" unit="bytes" />
        </Category>
      </JVMHealth>
    </Source>
    <Source name="vizql" startport="9400" endport="9499">
      <TableauHealth>
        <Category name="External Query Cache" path="name=vizqlservice">
          <Counter name="ExternalAbstractQueryCacheHits" />
          <Counter name="ExternalAbstractQueryCacheMisses" />
          <Counter name="ExternalQueryCacheHits" />
          <Counter name="ExternalQueryCacheMisses" />
        </Category>
        <Category name="InProcess Query Cache" path="name=vizqlservice">
          <Counter name="InProcessAbstractQueryCacheHits" />
          <Counter name="InProcessAbstractQueryCacheMisses" />
          <Counter name="InProcessQueryCacheHits" />
          <Counter name="InProcessQueryCacheMisses" />
        </Category>
        <Category name="Visual Model Cache" path="name=vizqlservice">
          <Counter name="VisualModelCacheHits" />
          <Counter name="VisualModelCacheMisses" />
          <Counter name="VisualModelCachePartialHits" />
        </Category>
        <Category name="Image Cache" path="name=vizqlservice">
          <Counter name="ImageCacheHits" />
          <Counter name="ImageCacheMisses" />
        </Category>
        <Category name="Sessions" path="name=vizqlservice">
          <Counter name="ActiveSessions" />
        </Category>
      </TableauHealth>
    </Source>
    <Source name="dataserver" startport="10000" endport="10299">
      <TableauHealth>
        <Category name="Overall Metrics" path="name=dataserver">
          <Counter name="ActiveSessions" />
          <Counter name="RequestsCount" />
        </Category>
      </TableauHealth>
    </Source>
  </MBean>
</Counters>

**Comment by SriVV** [comment]
[Counters - Copy.config.txt](https://github.com/tableau/TabMon/files/418811/Counters.-.Copy.config.txt)

**Comment by jmangue** [comment]
Heya SriVV,

Your config looks correct.

In 9.3 many of the JMX counters changed names & format.  The config you have is for 9.2.  We are tracking a work item to update the JMX counter code to handle 9.3 & 10.0 in Issue #55.  Still, I would expect to see some of the JMX counters come through in your data set.. 

One thing to check is to search in your logs for the phrase "Loading MBean counters..".  Below this you should see several occurrences of the log line "Opened connection to JMX server" along with a hostname and port number.  If you don't see these it's possible there is a communication issue between TabMon and Tableau Server JMX.

**Comment by SriVV** [comment]
We used to see this in the past and we asked our network team to open all ports and we no longer see any reference to JMX or "Loading MBean counters.." in our logs. Are we saying that it should show loading MBean counters in TabMon.log.txt irrespective of communication issue or NOT ??

**Comment by jmangue** [comment]
With the config you are using you should see "Loading MBean counters.." when the TabMon service first starts up, whether there is a communication issue or not.

The "Opened connection to JMX server" messages on the other hand will only show up if there is not a communication error.

**Comment by SriVV** [comment]
I don't see any JMX references in logs. I am seeing below references to process
2016-08-15 17:28:37,629 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\servername\Perfmon\Process\Working Set\tdeserver64#3: Instance 'tdeserver64#3' does not exist in the specified Category.
2016-08-15 17:28:37,644 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\servername\Perfmon\Process\Working Set\tdeserver64#2: Instance 'tdeserver64#2' does not exist in the specified Category.
2016-08-15 17:28:37,660 [5] DEBUG TabMon.Counters.Perfmon.PerfmonCounter - Error sampling counter Primary\servername\Perfmon\Process\Working Set\tdeserver64#5: Instance 'tdeserver64#5' does not exist in the specified Category.


Do these provide any information we are looking for ??

**Comment by jmangue** [comment]
Those errors are not related to JMX and are a consequence of those processes being ephemeral.

Can you send me the full contents of your Logs directory as well as Counters.config & TabMon.config files?

**Comment by jmangue** [comment]
Closing due to age.  The ephemeral process errors were fixed in TabMon 1.1.
