### ISSUE TITLE
TabMon Setup failed

### ISSUE THREAD

**Issue by simi676** [tableau/TabMon#90]
Hi 

I am trying to install TabMon and I am getting setup error.  I am getting the error with 

Applying execute package: PostgresInitializer, action: Install, path: C:\ProgramData\Package Cache\{8C3192D8-9D23-4C20-BBCE-459B898CD916}v1.0.0.0\TabMonServiceInstallerDBInitializer.msi.

I followed the exact steps as mentioned by Justin Mangue in one of the tableau community posts https://community.tableau.com/message/428610#428610.

The thing is I can't find {8C3192D8-9D23-4C20-BBCE-459B898CD916}v1.0.0.0 in my package cache.
I uninstalled and reinstalled a couple of times but still not bale to find the unique id .

Any leads would be very much appreciated !
Thanks to you guys for this awesome product.

**Comment by simi676** [comment]
Hi ,

I have tried to regenerate the TabMonServiceInstallerDBIntializer.msi for a couple of times by running the TabMon initial install but this file is never generated in my Program Cache. 

The program cache only contains  and below is the error log file.
Please help !

![programcache](https://cloud.githubusercontent.com/assets/12118970/17972431/549fe340-6aa4-11e6-860d-d1d7ecccd1f7.PNG)

**Comment by danjrahm** [comment]
Hello,

So far the TabMon.txt file doesn't offer a whole lot of context for why the initialization is failing. Normally these issues are due to a the initialization powershell script not successfully running.

The quickest way to resolve this will be to perform a manual postgres install and initialization. To perform this please follow the instructions in Appendix A of the linked user guide.
https://github.com/tableau/TabMon/blob/master/TabMonService/Documentation/UserGuide.pdf

If there are any other issues please let me know.

Thanks,
Dan

**Comment by simi676** [comment]
Hi ,
I tried to do a manual postgres install but my organization doesn't allow that.  What would be the alternative workaround for this set up?  My final aim is to be able to connect to the TabMon database in postgres. Is it not possible to login into postgres with my login credentials for TabMon database via Tableau?

Thanks !

**Comment by jmangue** [comment]
If a security policy is blocking TabMon from installing Postgres and you can't install it manually either, then you are basically left with two options:
1) Use an already existing Postgres database somewhere in your system for TabMon. You would need to work with one of your DBA's to set you up with an isolated database instance & user credentials.  Do not use Tableau Server's repository for TabMon!
2) Use TabMon in CSV output mode.

Hope that helps.

**Comment by simi676** [comment]
Thanks Justin. Definitely, I would try both the options and see which works best. I will let you know if I have further questions.

Thanks !

**Comment by simi676** [comment]
Hi Justin,

Sorry for being so late. I was able to install TabMon successfully.

Thanks for all your help !

**Comment by jmangue** [comment]
No problem simi!  Glad you got it working.  Closing this out.
