### ISSUE TITLE
Missing vizql counters

### ISSUE THREAD

**Issue by dsunsheng** [tableau/TabMon#97]
Hi, we have a Tableau Server V10 installed on a single Windows Server. We also installed TabMon on this server. Service.jmx_enable is True and when starting TabMon, the port scanning process found the port for vizql. However, we are still missing the all counters listed in following config. All these columns are missing from the database. (BTW, other counters are working fine and it is amazing information, Nice work)

```
</Source>
<Source name="vizql" startport="9400" endport="9499">
  <TableauHealth>
    <Category name="External Query Cache" path="name=vizqlservice">
      <Counter name="ExternalAbstractQueryCacheHits" />
      <Counter name="ExternalAbstractQueryCacheMisses" />
      <Counter name="ExternalNativeQueryCacheHits" />
      <Counter name="ExternalNativeQueryCacheMisses" />
    </Category>
    <Category name="InProcess Query Cache" path="name=vizqlservice">
      <Counter name="InProcessAbstractQueryCacheHits" />
      <Counter name="InProcessAbstractQueryCacheMisses" />
      <Counter name="InProcessNativeQueryCacheHits" />
      <Counter name="InProcessNativeQueryCacheMisses" />
    </Category>
    <Category name="Visual Model Cache" path="name=vizqlservice">
      <Counter name="VisualModelCacheHits" />
      <Counter name="VisualModelCacheMisses" />
      <Counter name="VisualModelCachePartialHits" />
    </Category>
    <Category name="Image Cache" path="name=vizqlservice">
      <Counter name="ImageCacheHits" />
      <Counter name="ImageCacheMisses" />
    </Category>
    <Category name="Vizql Sessions" path="name=vizqlservice">
      <Counter name="ActiveSessions" />
    </Category>
  </TableauHealth>
  <TableauInstrumentation>
    <Category name ="Bootstrap Session" path="00=api,01=vqlweb,name=bootstrapSession">
      <Counter name="DurationMean" />
      <Counter name="ExceptionCount" />
      <Counter name="InvocationCount" />
    </Category>
  </TableauInstrumentation>
</Source>
```

Anything else we can provide to assess the problem?

**Comment by jmangue** [comment]
Hi dsunsheng,

Interesting.. I just went through and confirmed that those counters are expected to exist in 10.0.

Are there any clues in your TabMon logs?  The next troubleshooting step would probably be to try and connect to JMX manually using a client such as Oracle Mission Control, and verify what counters are present.

**Comment by jmangue** [comment]
Hi dsunsheng,

Any updates on this?

One other thing to check would be to verify that vizql is running on base port 9400.

**Comment by jmangue** [comment]
Closing out due to inactivity, please reopen if you still need help.
