### ISSUE TITLE
Which procedures are necessary to perform a setup and config of Tabmon on a distributed environment?

### ISSUE THREAD

**Issue by ItaloMaineti** [tableau/TabMon#98]
Hello,

I have a distributed environment composed by 3 Tableau 9.3 servers as below:

1) Tableau 9.3 Primary Server (10.56.171.101)
2) Tableau 9.3 Worker I Server (10.56.171.102)
3) Tableau 9.3 Worker II Server (10.56.171.103)

I have installed the Tabmon in all Tableau Servers of this environment and the Postgres Database was installed only on Primary Server, using the embedded postgres setup of Tabmon.

The "TabMon.config" is set as below:

```xml
<?xml version="1.0"?>
<!-- TabMon user settings: set these as required -->
<TabMonConfig xmlns="TabMon">
  <!-- Output mode.  "DB" for database, "CSV" for flat-file export -->
  <OutputMode value="db"/>
  <!-- Polling rate, in seconds -->
  <PollInterval value="60"/>
  <!-- Target cluster & host configuration -->
  <Clusters>
    <Cluster name="Primary">
      <Host name="10.56.171.101"/>
      <Host name="10.56.171.102"/>
      <Host name="10.56.171.103"/>
    </Cluster>
  </Clusters>
  <!-- Results output database Configuration-->
  <Database name="TabMon" type="Postgres">
    **<Server host="10.56.171.101" port="5432"/>**
    <User login="tabmon" password="password"/>
    <Table name="countersamples"/>
    <!-- Generate indexes on service startup. -->
    <Indexes generate="true">
      <Index column="timestamp" clustered="true"/>
      <Index column="machine" clustered="false"/>
      <Index column="instance" clustered="false"/>
    </Indexes>
    <!-- Automatically drop data rows older than the specified number of days.
         Set enabled="true" to turn this on. -->
    <PurgeOldData enabled="true" thresholdDays="180"/>
  </Database>
</TabMonConfig>`
```

* The service of TabMon on service.msc is set with same user that is admin on all servers.
* The service of TabMon-Postgres is set with NT AUTHORITY\SYSTEM.
* The windows firewall was turned off on all servers.

With all config above, when I try to start TabMon, the error below occurs:

```
`2016-10-31 11:26:36,955 [5] ERROR TabMon.TabMonAgent - Failed to initialize counter sampler using counters from configuration file: The network path was not found.

Aborting..
2016-10-31 11:26:36,955 [5] FATAL Topshelf.Runtime.Windows.WindowsServiceHost - The service did not start successfully
Topshelf.TopshelfException: The service did not start successfully (returned false).
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStart(String[] args)
2016-10-31 11:26:36,971 [1] ERROR Topshelf.HostFactory - The service terminated abnormally
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabMon.TabMonAgent.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose(Boolean disposing)
   at TabMonService.TabMonServiceBootstrapper.Dispose()
   at Topshelf.Builders.ControlServiceBuilder`1.ControlServiceHandle.Dispose()
   at Topshelf.Runtime.Windows.WindowsServiceHost.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at Topshelf.Runtime.Windows.WindowsServiceHost.Run()
   at Topshelf.HostFactory.Run(Action`1 configureCallback)`
```

If I remove the Workers set on "TabMon.config" (2 lines below) the service starts with no error.

```xml
      <Host name="10.56.171.102"/>
      <Host name="10.56.171.103"/>
```
 
I forgot to perform any procedure in the configuration? What procedures are necessary to perform a setup and config of Tabmon on a distributed environment? 

Regards

Italo

**Comment by jmangue** [comment]
Hi ItaloMaineti,

Sorry to hear you're hitting some difficulties on setup.  Can you please try out the troubleshooting steps in this article: http://www.sensiblesoftware.com/weblog/2012/06/14/resolving-network-path-is-not-found-errors/
 -- primarily the part about the list of services that need to be running on either end, as well as making sure NetBIOS is enabled.

One note on your deployment -- if you are using TabMon to do remote polling, you only need to have TabMon installed on *one* machine.  It should not be installed on each of your workers.  Ideally, TabMon is located on a separate VM and not one of your Tableau Server machines at all.

Let me know how it goes!

**Comment by ItaloMaineti** [comment]
Hello Justin,

Thank you by the article, my RemoteRegistry service was disabled and stoped. When I enabled and start the RemoteRegistry on Services.msc, the Tabmon started without problem! Solved!

These recomendations was discribed on the article.

Below the command used to enable and start the services remotely.

#########################################
Configuração dos serviços como automatico
#########################################
sc \\10.56.171.101 config RemoteRegistry start= auto
sc \\10.56.171.102 config RemoteRegistry start= auto
sc \\10.56.171.103 config RemoteRegistry start= auto

#########################################
Start do serviço RemoteRegistry nos servidores de Desenvolvimento
#########################################
sc \\10.56.171.101 start RemoteRegistry 
sc \\10.56.171.102 start RemoteRegistry
sc \\10.56.171.103 start RemoteRegistry

#########################################
Start do serviço TabMon no servidore SCWTD0172CLD 
#########################################
sc \\10.56.171.101 start TabMon


Regards
Italo

**Comment by jmangue** [comment]
Glad to hear you got it working!  Closing this out.
